### ISSUE TITLE
Inclusion of binary data into a text-based format

### ISSUE THREAD

**Issue by lrosenthol** [WICG/webpackage#10]
[The section on the index ](https://github.com/dimich-g/webpackage#use-case-optional-content-index) says that compression may be permitted, but that may/will yield binary data.  However, because the header of the is document is text - most sniffers will consider this a text file and treat it accordingly (eg. screwing up line endings).

Either require that all data be text-encoded (eg. BASE64) or use a binary format.

**Comment by bmeck** [comment]
@lrosenthol I do not view this as a problem. Opening a text editor on the file format and editing is not something I see as a goal.

**Comment by lrosenthol** [comment]
@bmeck The problem isn't manual editing.  The problem is systems that determine whether to automatically convert line endings of injected files based on sniffing the beginning of file's content (eg. git).

**Comment by bmeck** [comment]
@lrosenthol would using hpack or something to turn the headers into something a sniffer would not see as ASCII be sufficient? I'm not terribly moved by automatic conversion by git etc. as other files suffer similar problems.

**Comment by lrosenthol** [comment]
@bmeck  - Assuming you mean [this hpack](https://http2.github.io/http2-spec/compression.html), it isn't viable as that only works for headers not arbitrary data.   
And just because the other kids are jumping off the bridge doesn't mean we should too :).  We know it's wrong - let's not do it...

**Comment by bmeck** [comment]
@lrosenthol my understanding is that the headers were the cause for concern related to sniffers. I do not wish to use hpack on bodies. So, I was saying something like hpack (maybe not hpack) to compress the headers might be sufficient.

**Comment by groundwater** [comment]
I think binary data will be common place.

1. webassembly
2. images/audio/video
3. encrypted data

I don't know how good/bad BASE64 encoding is, but it's never been a great story for JSON. Would a few magic bytes fool the sniffers?

**Comment by lrosenthol** [comment]
there is nothing wrong with BASE64 - it's been in widespread use for
decades.  However, it has the downside of bloating file size (since it is
obviously larger than the binary equivalent).

One way to address this problem is to force a web package to be a binary
format, in the same way that PDF did 20+ years ago (and continues to do).
Put a string of high order ASCII early on in the file (eg. as part of the
format header).  That should hopefully fool the sniffer to consider it
always a binary file and thus allowing enclosed binaries.

On Fri, Dec 30, 2016 at 3:46 PM, Jacob Groundwater <notifications@github.com

**Comment by groundwater** [comment]
Thank you @lrosenthol!

> it has the downside of bloating file size

That was honestly the only downsize I could think of. Given that one problem this project aims to solve is packaging for folks with low or limited access, I think file size is important.

> the same way that PDF did 20+ years ago

What I love about this solution is that we're copying something that already works!

@bmeck regarding hpack, I don't know much about the format, but it sounds like it has the upside of both reducing file size, and passing the sniff test. It sounds like the downsize is increased complexity of creating and parsing the package. For a moment, assuming the binary sniffing problem was solved, are there still benefits to hpack?

**Comment by bmeck** [comment]
@groundwater file size is a big win, allowing arbitrary extension headers is a possible win. Stateful compression like hpack can have a downside in that you have to preserve state if you want to extract  only one part of the archive and leave the rest intact.

**Comment by groundwater** [comment]
@bmeck 

> file size is a big win

I agree! Just to ask, is this something that could be seen as a v2.0 optimization? Or would this need to be part of the spec out of the gate.

> allowing arbitrary extension headers is a possible win

I am not sure what this means, but it sounds interesting. Can you explain a little more?

> Stateful compression like hpack can have a downside in that you have to preserve state if you want to extract only one part of the archive and leave the rest intact.

Correct me if I'm wrong, but it sounds like this is solvable _with good tooling_. But there is a cost in creating that tooling.

**Comment by lrosenthol** [comment]
There are (basically) three different approaches to archival compression

- Compress the entire thing (ala .tar.z)
- Compress each file/object individually (ala ZIP)
- Block-based compression

The latter is the most complex and yields somewhat larger files, but with
the advantage of being able to do partial decompression and/or updates.
It's also (AFAIK) still under a variety of patents from the 90's when it
was first developed.

You have to make a decision about which up front as it's part of your
format design.

**Comment by bmeck** [comment]
> > allowing arbitrary extension headers is a possible win

> I am not sure what this means, but it sounds interesting. Can you explain a little more?

Things that are not well known headers a like `X-Special-Header: ...` in HTTP. In the actual HTTP 1.1 RFC extensions are not required to start with `X-` and the use of that prefix is deprecated, I just used it to make a point. 

> Correct me if I'm wrong, but it sounds like this is solvable with good tooling. But there is a cost in creating that tooling.

The way hpack works it can index existing field/value pairs https://http2.github.io/http2-spec/compression.html#compression.based.attacks has some more details on various design considerations to take note of due to this.

**Comment by jyasskin** [comment]
What are the technical constraints here? I assume UTF-8 isn't sufficiently non-text to convince sniffers that they've found a binary file. How close to the beginning of the file do non-UTF-8 sequences need to appear in order to convince sniffers that the file's binary?

**Comment by jyasskin** [comment]
I've finally realized the benefits of @bmeck's suggestion to use [HPACK](http://httpwg.org/specs/rfc7541.html). Even if we forbid parts from adding entries to the [dynamic table](http://httpwg.org/specs/rfc7541.html#dynamic.table), we get the following benefits:
1. The format is obviously binary and will appear right at the beginning of the package, solving #10.
2. The [static table](http://httpwg.org/specs/rfc7541.html#static.table.definition) will reduce the size of many common headers.
3. The [Huffman code](http://httpwg.org/specs/rfc7541.html#huffman.code) will reduce the size of many uncommon headers and values.

**Comment by lrosenthol** [comment]
Correct, UTF8 is still text.   Usually sniffers tend to search the first
2048 bytes or less.

As for HPACK - I am not seeing how that will help.  The large sizes for web
packages aren't going to be the headers but the actual data of each part.

**Comment by inexorabletash** [comment]
Reading through CBOR, I noticed the bit on [Self-Describe CBOR](https://tools.ietf.org/html/rfc7049#section-2.4.5) which roughly says you can freely prepend 0xd9d9f7 as a CBOR magic number, which is also carefully chosen to not be a valid UTF-8 or UTF-16 sequence. I don't know if mandating a leading "tag 55799" for webpackage has been discussed elsewhere (I'm a noob here) but it might be useful for making the very start of the package less sniffable as text?

**Comment by jyasskin** [comment]
The beginning of the current format is "83 48", which isn't valid UTF-8, but it is valid UTF-16. Do we need to prevent the format from being valid UTF-16?

**Comment by bmeck** [comment]
@lrosenthol can we move this to https://github.com/WICG/webpackage/issues/47 ?

**Comment by lrosenthol** [comment]
Yes, that's fine with me.  Thanks!
