### ISSUE TITLE
will support packaging only subresource ?

### ISSUE THREAD

**Issue by Jxck** [WICG/webpackage#101]
in ES modules, we need to fetch a lot of module files.
increasing requests cause a performance issue. ([10k 1kB load is 10 times slower than single 10MB load](https://docs.google.com/document/d/1ds9EEkcDGnt-iR8SAN-_7nsOfw7gsMfhZjzZ_QAIyjM/edit))

h2 will reduce connection handshake/establish, but doesn't reduce request/response itself which browser handles inside.

but reducing files via bundling like webpack is less merit of es modules(ex caching etc). 

same things happens for image. so we sometimes concatting them aka Sprite.

current spec seems packaging main-resource + sub-resource in 1 file.
so if webpackage support or have candidate to package lot of resources into 1 package(not include main-resoruce) seems solve fetching performance problem.
expected behavior is fetching single response but unpackaging in browser and handling/caching like separated ESModules/ImageIcons/StyleSheets etc.

**Comment by yoavweiss** [comment]
This is a use case I discussed with @jyasskin, @addyosmani and @patrickkettner.

I think using webpackage as a bundling format is an interesting use case, and will provide the same compression benefits bundling currently provides without all its downsides. I think it can and should be addressed by these specifications, but will require some extra mechanisms to enable it.

I guess the first step is to send out a PR outlining this use-case.

**Comment by yoavweiss** [comment]
Filed a use case PR. Beyond that, we also need to define a mechanism that will let the browser:
* Know that a package download is required
* Know which resources are covered by a certain package, so that their requests won't race with the package's response. Such a mechanism can use some form of digest that will include all the URLs in the package and will be delivered with the "package is required" markup.

Straw-man for such markup may look like:
`<link rel=package href="js_bundle" digest="bcfd23234989734abdcef">`

**Comment by Jxck** [comment]
It's not only for esmodules but also image, style, font, favicon etc.

I have 2 plan for this in my mind.

dump them in rough.

## `<package>` like `<picture>` way for selective `<img>`

for example

```
<package src=bundle.wpac>
  <!-- backword compat for no-package -->
  <script type=module src=react.js>
  <script type=module src=moment.js>
  <script type=module src=main.js>

  <!-- backword compat for no-module -->
  <script type=nomodule src=bundle.js>

  <!-- css -->
  <link rel=stylesheet href=bootstrap.css>
  <link rel=stylesheet href=style.css>

  <!-- favicon -->
  <link rel="shortcut icon" href="favicon.ico">
</package>
```

browser which support webpackaging fetches `<package>` resource.

```
GET /bundle.wpac HTTP/1.1
Accept-Encoding: wpac
```

server responses bundled.wpac

```
HTTP/1.1 200 OK
Content-Encoding: wpac

packaged all resouces
```

unpack them and treat each file as fetched via reach request


in this time we have 2 consideration


- what is cache time for wpac ?
  - longest cache in package
- what is the cache information for each modules ?
  - wpac format should contain meta information about how long each modules could cache
- browser should not always fetch bundle.wpac, how to decide ?
  - while bundle.wpac cache is valid, fetch each files. if bundle.wpac cache is invalid, fetch bundle.wpac
- what happen if bundle.wpac doesn't include `moment.js` ?
  - fetch moment.js again according to `<script>`


this requires adding new tag `<package>` and adding meta information for packaging format.


## Content-Encoding and 209 Already Respond


browser requests

```
GET index.js HTTP/1.1
Accept-Encoding: wpac

GET moment.js HTTP/1.1
Accept-Encoding: wpac

GET bootstrap.css HTTP/1.1
Accept-Encoding: wpac
```


browser sends accept encoding wpac so server can response in single pack.

and server responses


```
HTTP/1.1 200 OK // for index.js session
Content-Encoding: wpac
Packed-Content: index.js
Packed-Content: moment.js
Cache-Control: max-age=3600
// wpac body


HTTP/1.1 209 Already Respond // for moment.js session
Cache-Control: max-age=1024
// empty body

HTTP/1.1 209 Already Respond // for bootstrap.css
Cache-Control: max-age=3600
// empty body
```

1st response include packaged resouces. browser unpack them in files which treat as they are respond in Status Code 200 each.

if client already cached wpac, but only index.js is expired, request index.js only.


in this case, client/server can handle via content-negotiation
no adding semantics for html but need new response status code `209 Already Respond`

- why Already Reponed
  - need to close http session. but browser don't need to care much about response which already respond in Pack.
- what is HTML look like ?
  - as-is, content-negotiation is opt in.
- what is in package ?
  - server knows which is depended in index.js, so server can bundle them, and show them in Packed-Content header
- what will happen in unsupported browser
  - work as is
