### ISSUE TITLE
Details of exactly what is hashed (both for individual entries and the package itself) are missing

### ISSUE THREAD

**Issue by lrosenthol** [WICG/webpackage#12]
There is nothing specified for exactly which bytes are hashed - either for an individual file/resource for the header or the index.  

Do you include the boundary string?  Do you include any closing line endings?

**Comment by bmeck** [comment]
see note about each resource having its HEADER+BODY signed in : https://github.com/dimich-g/webpackage/blame/master/README.md#L308

My PR rephrased in a few places to make more explicit in https://github.com/dimich-g/webpackage/pull/23

It might be prudent however to change the phrasing of https://github.com/dimich-g/webpackage/blame/master/README.md#L312 to state that nested packages as signed as opaque entities as it sounds currently like nested packages are not something that the root package can verify as being correct currently.

**Comment by bmeck** [comment]
Just noticed, the certificates are not signed in the Content-Index examples; unsure if this is intentional, but seems like just an accident.

**Comment by bmeck** [comment]
@lrosenthol if certificates are signed is the rest covered?

**Comment by lrosenthol** [comment]
You can't sign a certificate with itself - but you could sign the
certificates from a nested package with the certs from the parent - that
would be perfectly fine.

**Comment by jyasskin** [comment]
Arguably, these details can go in the draft specification rather than the explainer, but it's probably time to start that specification and add these details, so we can iterate on them.

**Comment by jyasskin** [comment]
#36 now specifies exactly which bytes are hashed and signed, so I believe this is fixed.
