### ISSUE TITLE
http and P2p

### ISSUE THREAD

**Issue by gedw99** [WICG/webpackage#128]
With PWA's rise, there is allot of action going on with P2P. 
Your browser is almost a web server now.
I am seeing so many different ways to do the security aspects for P2P. 
HTTPS is not designed to do P2P, so i wanted to raise this and se if there is any thoughts on this going forward.

I am expected to be told that this aspect is not part of the "WebPackage" spec and probably rightly so.
But i am trying to find where people are trying things out using golang to try to use HTTPS and P2p.

**Comment by jyasskin** [comment]
Web packages would be good content to transfer peer-to-peer, but this repository won't define the Javascript API to actually make P2P connections. At one point Mozilla was working on https://flyweb.github.io/ to provide this kind of API, but I suspect they've abandoned it.
