### ISSUE TITLE
Signatures not in compliance with EU law

### ISSUE THREAD

**Issue by lrosenthol** [WICG/webpackage#13]
As described in [Mandate M/460](http://www.e-signatures-standards.eu/activities), only certain signature format and standards can be legally used in the EU - and this proposal does not comply with any.  It would be better to align with at least one of them - most likely CAdES.

**Comment by bmeck** [comment]
Note various parts of these return 404s like https://docbox.etsi.org/ESI/Open/Latest_Drafts/ts-119172-1_v009-SignaturePolicyFramework-STABLE-DRAFT.pdf currently

**Comment by bmeck** [comment]
I gave it a read through (once is not enough for me to fully understand in depth though). It seems this is more around policy and I see nothing in WebPackage that prevents you from using the proper standards (it also allows you to create signatures outside the standard). What are the exact things that prevent compliance?
