### ISSUE TITLE
gen-certurl: turn this into a library so that other tool can depend on this

### ISSUE THREAD

**Issue by nyaxt** [WICG/webpackage#142]

**Comment by hajimehoshi** [comment]
Not sure the concrete plan.

**Comment by irori** [comment]
Now we have the [certurl package](https://github.com/WICG/webpackage/tree/master/go/signedexchange/certurl) which can be used as a library. ([example usage](https://github.com/irori/htxg-b1/blob/sxg-test/gae/cert_handler.go))
