### ISSUE TITLE
Validation cannot necessarily take place offline 

### ISSUE THREAD

**Issue by lrosenthol** [WICG/webpackage#15]
In the [discussion on signing](https://github.com/dimich-g/webpackage#use-case-signed-package-one-origin), it says
> The inclusion of certificate makes it possible to validate the package offline (certificate revocation aside, this can be done out-of-band when device is actually online).

This is only true in very few cases as you need to build an entire trust chain from that cert up to the root.  Most processors will not have local access to every cert - in which case, it will need to fetch them.

**Comment by dimich-g** [comment]
True, the full chain is necessary for validation. Intermediary certificates can be usually fetched automatically, based on info in the Authority Information Access (AIA) extension in a typical certificate. There is a paragraph on that at the end of FAQ in the Explainer.
Since a tool of some sort is required to sign a package, the same tool could make sure to fetch intermediate certificates and package them into the same package. Whether it is a part of the same resource or it has to be multiple 'certificate' parts all representing parts of the certificate chain is still somewhat an open question.

**Comment by lrosenthol** [comment]
You could indeed package up (a set of) intermediate certificates - but,
that may not be the same set that is used at validation time, depending on
the validation policy in place.  Different policies can lead to different
branches of the chain.   Also, you'd still (most likely) need to do
revocation checks, which require online access for full validation.
And then there is the whole "where do you get the CA certs from"
problem...(EUTL, OS, other?)

All solvable - as they are in other instances - but could lead to
interoperability issues...

**Comment by bmeck** [comment]
I think the point here was that your environment could supply the missing certs and/or your downloader could automatically check/fetch missing certs. "possible" does not mean always true in my mind. I am unclear on the specific interoperability issue you allude to except from collision and/or replacement of certs which are true in almost all systems (particularly if non-security based revocation/expiration is allowed to be ignored).

**Comment by lrosenthol** [comment]
If you read the relevant standards around signature validation (such as
those form the EU's eIDAS regulations, incl EN 319 102-1 v1.1.1 and TS 119
172-1), you will see that the building of the trust chain for validation is
controlled by a number of factors including signature policies. Those
policies have impact on the interoperability, as does the selection of CA
repository.

Again, these are all solved problems in DOCUMENT signature space - which is
not the same as web content/TLS signature validation.

**Comment by bmeck** [comment]
@lrosenthol I was not thinking of looking at those, so if you have other relevant documents it might be good to share those.

**Comment by dimich-g** [comment]
@lrosenthol thanks for the references! Need to digest a bit :)
