### ISSUE TITLE
Case-different keys in CBOR exchange headers

### ISSUE THREAD

**Issue by irori** [WICG/webpackage#161]
CBOR representation of exchange headers must be canonically-serialized, which means maps must not have multiple entries with the same key.

However, they still can have duplicated HTTP header fields with case differences. For example:
```
[
  {
    ':url': 'https://example.com/'
    ':method': 'GET',
  },
  {
    ':status': '200',
    'Content-Type': ...
    'content-type': ...
  }
]

```
Should the spec explicitly forbid such duplicated headers? Or specify that header names must be stored in lower-case?

**Comment by davidben** [comment]
HTTP/2 requires that everything be lowercase. This isn't exactly HTTP/2 since `:url` is different, but it borrows `:method` and `:status` from HTTP/2, so aligning there seems reasonable. No reason to allow multiple spellings of the same thing.

**Comment by jyasskin** [comment]
Yep, PTAL at #163.
