### ISSUE TITLE
gen-certurl should be updated to follow latest spec draft

### ISSUE THREAD

**Issue by nyaxt** [WICG/webpackage#165]
https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#cert-chain-format

**Comment by hajimehoshi** [comment]
ack

**Comment by nyaxt** [comment]
@twifkak You may want to update your software to use nyaxt branch for gen-certurl before the change goes in.

**Comment by twifkak** [comment]
Thanks; will do. Please cc me on the PR for this.
