### ISSUE TITLE
OCSP / SCT requirements of the cert-chain

### ISSUE THREAD

**Issue by irori** [WICG/webpackage#175]
https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#cert-chain-format

> 2. The first certificate’s ocsp value *if any* MUST be a complete, DER-encoded OCSP response for that certificate

This reads main certificate's ocsp property is optional, but actually it's required in the step 6.3 of [Cross-origin trust](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#cross-origin-trust)?

> 3. Each certificate’s sct value MUST be a SignedCertificateTimestampList for that certificate

- Add "if any" since SCTs may be embedded in the `cert` or `ocsp`? (#171)
- The step 6.4 of [Cross-origin trust](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#cross-origin-trust) uses only SCTs for main certificate. If `sct` is to provide a channel to supply SCTs instead of the TLS extension, should the spec say that subsequent certificates MUST NOT have a `sct` value?

@jyasskin @hajimehoshi @nyaxt

**Comment by twifkak** [comment]
Yeah, my understanding is the spec allows the same-origin response to omit ocsp and sct, in which case the intermediary must collect and attach them. Question: If an intermediary made a stricter requirement that it would only ingest SXGs that include these, would it be a bad citizen?

**Comment by irori** [comment]
These are covered by #246.
