### ISSUE TITLE
explainer: Should prefetch recursion have a limit?

### ISSUE THREAD

**Issue by twifkak** [WICG/webpackage#185]
If A prefetches sxg_0, which includes a preload for sxg_1, which includes a preload for sxg_2, ... This could lead to unbounded prefetches. Perhaps include a limit like https://fetch.spec.whatwg.org/#ref-for-concept-request-redirect-count%E2%91%A0.

**Comment by twifkak** [comment]
cc @kinu

**Comment by jyasskin** [comment]
I think this issue belongs in the https://github.com/w3c/resource-hints/ repository where prefetch is defined. I don't see anything specific to signed exchanges here.
