### ISSUE TITLE
Increment ver num on "implementation checkpoint"

### ISSUE THREAD

**Issue by nyaxt** [WICG/webpackage#186]
Chromium would like to start adding support for next "implementation checkpoint".
Can we increment ver num on https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl.html#rfc.section.5.3 ?

**Comment by jyasskin** [comment]
Yes ... do you have a feeling for the subset of https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html that you'll be able to implement for the next checkpoint?
