### ISSUE TITLE
Request for fixed length magic string: "sxg1-"

### ISSUE THREAD

**Issue by nyaxt** [WICG/webpackage#191]
In the current spec draft, the magic string is allowed to be arbitrary length for implementation drafts.

> Note: RFC EDITOR PLEASE DELETE THIS NOTE; The implementation of the final RFC MUST use this file signature, but implementations of drafts MUST NOT use it and MUST use another implementation-specific string beginning with “sxg1-“ and ending with a 0 byte instead.

This makes its streaming parsing non-trivial, since we need to scan for `"\0"` to appear, rather than reading fixed length record.

Two proposals:
- Allocate fixed length (8bytes?) for the magic string field, and pad the rest of the bytes `"\0"` 
  - Will file a PR for this
- Separate version field?

**Comment by nyaxt** [comment]
We would like to simplify the decoder which would live in the browser process as much as possible. I will draft a change that basically does:
```
"sxg1" magic + 3byte ver + 3byte siglen + 3byte hdrlen + ...
```

> I think an implementation can parse the current format by reading as many bytes as the longest magic string it supports, and then memcmp'ing against each of the magic strings including their trailing '\0'.

Yes, but it would require concatenating the overread portion to the start of {signature,headers} buffer.

**Comment by davidben** [comment]
> Yes, but it would require concatenating the overread portion to the start of {signature,headers} buffer

It is also possible that the signature/headers buffer may be smaller than the overread and you go into the body itself.

That said, you likely should be doing this anyway because issuing small reads at a time is not very efficient. (I don't remember being asked to review any CLs to implement the new format... I assume  they're just still in progress?) If you look at Chromium's HTTP/1.1 implementation, we read data in large chunks at a time and, if we got more or less than the full HTTP headers, we just handle that case.

**Comment by nyaxt** [comment]
I haven't written any code yet. (Mainly landing golang lib impl right now)

The current impl for the old format basically issues 3 reads at the minimum:
- SignedExchangeHandler: Read fixed header's header === {magic, headerLen}
- SignedExchangeHandler: Read CBOR header of headerLen
- MercleIntegritySourceStream: Read payload
  - SignedExchangeHandler moves ownership of the `source_` stream to MercleIntegritySourceStream

We can basically keep this 3+ read scheme if the new "header's header" is const, but needs to do buffering (as @davidben mentioned) to handle variable len magic.

> That said, you likely should be doing this anyway because issuing small reads at a time is not very efficient. (I don't remember being asked to review any CLs to implement the new format... I assume they're just still in progress?) If you look at Chromium's HTTP/1.1 implementation, we read data in large chunks at a time and, if we got more or less than the full HTTP headers, we just handle that case.

I discussed this a bit with @irori.

We are a bit hesitant to do our own buffering in SignedExchangeHandler until we are sure that this is a major performance bottleneck.
- We expect the format to evolve in the short term so we want to keep the implementation as simple as possible at this point.
- Getting rid of the `source_` move to MercleIntegritySourceStream is non-trivial. We need to either:
  - Modify MerkleIntegirtySourceStream to take additional ctor param for the overread portion, while this makes it divert from other FilterSourceStreams impl.
  - Make SignedExchangeHandler a SourceStream so it could proxy Read() calls.

**Comment by kinu** [comment]
Doing small reads at parsing layer and making buffered read in the underlying layer for efficiency can be decoupled in the implementation, I think impl concerns can be probably addressed (we chatted potential feasible impl options with @nyaxt, @irori and @horo-t too).

@davidben -- one thing that's a bit unclear to us is your stance on non-deterministic/streaming parsing. Once you pushed back the format that requires streaming parsing in favor of fixed length format, while this time we say that the variable length is preferable or okay in the newer format. What is driving the difference, is that the level of required complexity?

**Comment by kinu** [comment]
I see, that makes a lot sense to me now, thanks @davidben and @jyasskin for better clarification!
