### ISSUE TITLE
Clarify how we handle permanent diffs between impl checkpoint and the main draft (e.g. `MI` vs `MI-draft2`)

### ISSUE THREAD

**Issue by kinu** [WICG/webpackage#197]
I suppose the latest draft of the -impl checkpoint basically follows the latest responses draft ('the main draft) with some gaps, so a typical workflow could be like to keep cherry-picking changes from the latest responses into the latest impl draft.  However there are some diffs that are only tracked by the impl checkpoint but not in the main draft, e.g. like https://github.com/WICG/webpackage/pull/155 (`MI` vs `MI-draft2`).  I can see the reason not to track this in the main draft, but I'm afraid tracking such changes that only exist in some branch but not in the master responses draft may become a bit cumbersome, especially if we start to have multiple of such diffs.

Would it be possible to avoid doing this but instead put some instructions for the implementors in the main draft? (This is something @jyasskin mentioned as a potential alternative in some of our offline chat)  Or could we have some special section in the ChangeLog in the main draft so that all we need to cherry-pick can be still found in the main draft?

**Comment by jyasskin** [comment]
The current long-lived impl-only diffs are:

* MI->MI-draft2: Will be handled by https://github.com/martinthomson/http-mice/pull/8, probably with a reference in the main draft.
* A specific version number for the https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#internet-media-type-applicationsigned-exchange, for which I could have the existing editor's note call out draft-yasskin-httpbis-origin-signed-exchanges-impl.
* A couple TBDs have actual numbers. I could move these into the main draft.
   * mi-sha256 records must be <= 16kB.
   * application/signed-exchange's header length must be <= 512kB.


Did I miss any?

**Comment by kinu** [comment]
Sounds good, thanks!  We'll also watch https://github.com/martinthomson/http-mice/pull/8.  Moving some of the (tentative) actual numbers into the main draft sounds good too, or at least could be helpful for tracking changes from impl side (if you think having the change there is not harmful for future revisions).
Explicitly cc-ing @nyaxt in case he has other or additional thoughts.

**Comment by ioggstream** [comment]
As:

  - https://tools.ietf.org/html/draft-thomson-http-mice-02 is still in draft
  - there's a `Digest` header defined in https://tools.ietf.org/html/rfc3230 and https://tools.ietf.org/html/rfc5843

What do you think of proposing:

  - `mi-sha256` as an additional digest algo to rfc5843
  - introduce `*base64url*` in rfc3230

The outcome would be:

```
Digest: mi-sha256=*...*
```

**Comment by ioggstream** [comment]
Feedback from @martinthomson https://github.com/martinthomson/http-mice/issues/11

**Comment by jyasskin** [comment]
@ioggstream Let's keep discussing the Digest change over in the MICE repo.
