### ISSUE TITLE
Clarify #load-metadata Step 12.2 Metadata field

### ISSUE THREAD

**Issue by nyaxt** [WICG/webpackage#202]
cc: @jyasskin 

In the step 12.2 of "[Load a bundle's metadata](https://wicg.github.io/webpackage/draft-yasskin-dispatch-bundled-exchanges.html#load-metadata)", the text says:
> If "name"’s Metadata field is “No”, continue to the next triple.

I couldn't find where a Metadata field for a "name" is. Can we clarify the text here?

**Comment by jyasskin** [comment]
Step 8

> Let knownSections be the subset of the Section 6.2 that this client has implemented.

links to https://wicg.github.io/webpackage/draft-yasskin-dispatch-bundled-exchanges.html#section-name-registry, which has a Metadata field. It's probably worth including the link in 12.2 also.
