### ISSUE TITLE
Q: referrer from signed http exchanged page

### ISSUE THREAD

**Issue by Jxck** [WICG/webpackage#206]
1, navigate to https://example.com/a.sxg
2, a.sxg is signed by https://example.net so browser display it as https://example.net
3, clicking the link on https://example.net

in request of 3, which origin should on referrer header example.com (actual) or example.net (display) ?
(spec seems not mention this: https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html)

**Comment by kinu** [comment]
That should be example.net I believe.  Also example.net *is* the actual origin once UA is navigated to the exchange.  The [loading sketch in the explainer](https://github.com/WICG/webpackage/blob/master/explainer.md#signed-exchange-loading-sketch)  discusses some of these (while not clearly specifying details like referrers)

**Comment by Jxck** [comment]
is there any plan to add actual url(example.com) on request header like referrer ?

**Comment by jyasskin** [comment]
There's no plan to add a new `Referer`-like header that identifies the physical URL of the referrer. It's always possible, of course, given a strong enough use case.

**Comment by jyasskin** [comment]
#433 discusses the architectural question here.
