### ISSUE TITLE
Report failure to validate a signed exchange

### ISSUE THREAD

**Issue by jyasskin** [WICG/webpackage#214]
This should use http://wicg.github.io/reporting/.

**Comment by jyasskin** [comment]
This also needs to deal with the client being offline, and with clients who are fetching a signed exchange to avoid censorship/surveillance.

**Comment by twifkak** [comment]
It might be worth addressing two different use cases:

1. For distributors, to collect metrics on the efficacy of their validation algorithms and maybe trigger a removal of their cached copy. This would be on the outer exchange. If the SXG was prefetched first, it would only need to occur on the prefetch, not the navigation.

2. For publishers, to collect metrics on the validity of their publishing mechanism and maybe trigger a blacklist of that URL until the bug can be fixed. This would be on the inner exchange, and only occur on navigation, not prefetch.

There's a third case where the embedder is different from the distributor, but it's probably OK to make a simplifying assumption for now.

**Comment by horo-t** [comment]
Chromium implementation issue: https://crbug.com/910516

**Comment by horo-t** [comment]
@igrigorik suggested me to integrate with network-error-logging.
So I submitted an issue on NEL's repo.
https://github.com/w3c/network-error-logging/issues/99

**Comment by jyasskin** [comment]
I think this was solved by https://github.com/WICG/webpackage/pull/374.
