### ISSUE TITLE
Clarify what schemes should be allowed for URL fields in the signature

### ISSUE THREAD

**Issue by kinu** [WICG/webpackage#222]
Current Signed Exchange spec draft [says](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#rfc.section.3.1) `cert-url` and `validity-url` should be [an absolute-URL string](https://url.spec.whatwg.org/#absolute-url-string), but that could potentially allow multiple schemes than http/https (e.g. file and ws), while it doesn't seem to include data: URL.  It looks we'd better clarify what schemes should be allowed there.

**Comment by kinu** [comment]
https://github.com/whatwg/url/issues/68 made me think it's not covered there but rather in fetch spec, but yeah the URL spec covers broader concepts so it might actually cover it.

Reg: https://fetch.spec.whatwg.org/#fetch-scheme I doubt we want to include `about`, `blob` and `filesystem` schemes either, unless we're considering dynamic package generation done by a JS code.  Loading data from these URL would basically need upper layer context than HTTP layer (e.g. we need a concept of Web origin there), and implementing it will become harder.

**Comment by jyasskin** [comment]
I think `blob:` and `filesystem:` make sense for the newsreader app Jake demoed at I/O, where one SW stores signed exchanges for a bunch of other websites. That said, maybe we should assume bundles there, where the certificate can be stored inline.
