### ISSUE TITLE
Rename id-ce-testCanSignHttpExchanges

### ISSUE THREAD

**Issue by irori** [WICG/webpackage#229]
Came up in https://crrev.com/c/1103430/5/net/cert/asn1_util.cc#241:

@sleevi:
> Gotcha. $.02 (but not critical) is we should rename this to id-ce-canSignHttpExchangesDraft (or id-ce-draftCanSignHttpExchanges), it was the 'test' bit that caught me by surprise.

@jyasskin What do you think?

**Comment by jyasskin** [comment]
SGTM.
