### ISSUE TITLE
Idea: use of jws in Signature header

### ISSUE THREAD

**Issue by ioggstream** [WICG/webpackage#237]
What do you think about using a JWS inside a signature headers instead of redefining a Subset of jws claims?

Which is the Right Place for Such a discussion?

**Comment by ioggstream** [comment]
Understood. 

I was just trying to generalize this mechanism (eg. to other keys, ...) to use it as a non-repudiation standard (eg. respect to https://tools.ietf.org/id/draft-cavage-http-signatures-10.html) 

Sending `Signature` in every request/response would have done the job.

**Comment by jyasskin** [comment]
This is the right place for the discussion though. :) I'd like to make sure we appropriately address your use cases without getting side-tracked on the question of what format to use to encode signatures.

I'll point out that there are two kinds of generalization in here already:

1. The [ed25519key](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#signature-header) parameter allows basically the same header to work for https://github.com/mikewest/signature-based-sri.
1. When the public key is vouched by an X.509 chain, it could be something other than a domain-trusted key. For example, I expect [third-party security reviewers](https://tools.ietf.org/html/draft-yasskin-webpackage-use-cases-01#section-2.2.3) to sign with X.509 keys signed by something other than a Web CA.

Neither one addresses use in an HTTP *request*, and I do suspect that requests are different enough from responses that we shouldn't try to use the same header for both, but if you think we should, please suggest it in a new issue. (New to avoid the confusion with JWS.)

**Comment by ioggstream** [comment]
Hi @jyasskin and thank you very much for your reply!

> please suggest it in a new issue. (New to avoid the confusion with JWS.)
I moved the discussion to  #248
