### ISSUE TITLE
Specify how to handle too-long URLs?

### ISSUE THREAD

**Issue by twifkak** [WICG/webpackage#297]
The new spec allows fallbackURLs up to 65536 bytes long, but several existing browsers have lower limits than that. Perhaps the fetch spec should say how browsers should respond if the fallbackUrl is too long, or alternatively specify a minimum length they must support. Otherwise, browsers may behave differently (e.g. network error, redirect to fallback URL, or display a trimmed URL). Or is this already covered by some other part of Fetch?

**Comment by jyasskin** [comment]
This should be more general than just web packaging. For example, a too-long 302 redirect should behave the same way. I've filed whatwg/fetch#841 to track it.
