### ISSUE TITLE
Update loading spec per b2

### ISSUE THREAD

**Issue by twifkak** [WICG/webpackage#310]
https://wicg.github.io/webpackage/loading.html makes several mentions of `b1`. It will need to updated to refer to `b2`, as well as changes to where inner URL and payload digest are found, per the changes in #296 ([change log](https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl.html#change-log)). Possibly other things?

**Comment by jyasskin** [comment]
As long as Chrome supports loading both `b1` and `b2`, I'd like https://wicg.github.io/webpackage/loading.html#mp-http-fetch to accept both.

https://github.com/WICG/webpackage/pull/285 has a change to use the fixed location of the URL to handle the 'anything else' case, which you'll want to adopt if you update for `b2` anywhere else.

**Comment by nyaxt** [comment]
Chrome M70+ has dropped support for `b1` and only supports `b2`.

**Comment by jyasskin** [comment]
Removing `b1` from the loading spec sounds good then.

**Comment by jyasskin** [comment]
Fixed by #328.
