### ISSUE TITLE
How to open a .wpk file?

### ISSUE THREAD

**Issue by jimbojetlag** [WICG/webpackage#315]
I noticed there are some sample .wpk file sin https://github.com/WICG/webpackage/tree/master/examples . Do browsers open these files at this point? If not, how are they supposed to be opened by the end user?

**Comment by twifkak** [comment]
Hi! The examples in that directory are quite out-of-date. You can take a look at the instructions at https://github.com/WICG/webpackage/tree/master/go/signedexchange for how to generate a signed exchange, host it on a server, and browse it. They are intended for the end user, but for now, you need to enable an experimental flag in Chrome to view them.

**Comment by jimbojetlag** [comment]
That executable generates a .sxg file, when I tried to open it in Chrome by drang and drop, Chrome simply downloaded it.

How is it possible to share this package offline?

**Comment by twifkak** [comment]
With the current implementation, I believe sharing offline requires the receiver to host an HTTPS server. (i.e. Tools need to be built to enable this use-case.)

However, the spec specifically calls attention to the [local disk use-case](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#privacy-considerations), so I imagine this is a temporary situation. It may be worth adding support for `file:` in the [loading spec](https://wicg.github.io/webpackage/loading.html), though that may be difficult given that the Fetch spec that it monkeypatches leaves `file:` ["as an exercise for the reader"](https://fetch.spec.whatwg.org/#scheme-fetch).

**Comment by twifkak** [comment]
Ah yes, AFAIK, as of today, only a [snapshot of the signed exchanges spec](https://wicg.github.io/webpackage/draft-yasskin-httpbis-origin-signed-exchanges-impl.html) is implemented in Chrome, and not the bundled exchanges spec.

**Comment by gedw99** [comment]
What's happening with Firefox and edge in terms of adaption or flags ?
Is there a name for this functionality to allow checking on CanIUse website ?

**Comment by RByers** [comment]
Web packaging is really still being designed and implemented - with a focus on the privacy-preserving pre-rendering use case in Chrome. It's really nowhere near the point of being a useful feature for end users.

**Comment by KenjiBaheux** [comment]
Thanks for your interest!

In terms of *public* signals, the entry on chromestatus.com is up to date.
Stay tuned.
