### ISSUE TITLE
Document Node's use cases

### ISSUE THREAD

**Issue by jyasskin** [WICG/webpackage#33]
@bmeck, could you describe the use cases you're interested in for the packaging format, either in this issue or as a PR against the [`README.md`](https://github.com/dimich-g/webpackage/blob/master/README.md)?

**Comment by bmeck** [comment]
From an older call: https://docs.google.com/document/d/1iPHPLMUVimh8cZgB_vkO-XtmDrnanOMI9v5kfnwiv4U/view

**Comment by bmeck** [comment]
Mandatory:

* Signing
* Random Access
* Self Extracting capable

Important but not absolute requirements (would need some path to mitigate):

* Inter-package linking
* Nested packages
* Deduplication

Nice to have:

* Streaming
* Expiration

**Comment by bmeck** [comment]
mandatory requirements have been reached, feel free to mark closed
