### ISSUE TITLE
Transfer-Encoding in inner-exchange's response header.

### ISSUE THREAD

**Issue by nyaxt** [WICG/webpackage#336]
I've noticed the `Transfer-Encoding` header usage in SXG inner response headers.
We should specify how it will work.

- Option 1) Add to banned headers list.
- Option 2) Clarify in the loading spec that...
  - Option 2.a) Only compression schemes are allowed (Ban only `Transfer-Encoding: chunked`)
  - Option 2.b) They are ignored.

Note that Chromium ToT currently ~~ignores them. Which means, the response bytes are treated as they are raw bytes and doesn't go through decompressor/unchunking.~~ supports them

**Comment by nyaxt** [comment]
My personal preference is Option 1, since we always mice encode the response stream.

If we want compression, then we can compress the outer-response.
I think this aligns with the current bundling story where we want raw response bytes in order to achieve cross-resource compression.

**Comment by twifkak** [comment]
How do/should inner and outer `Transfer-Encoding` interact?

**Comment by davidben** [comment]
+1 to rejecting it.

Chromium accepting it is odd. Perhaps a quirk of MICE not being implemented at the same layer as other Content-Encodings? Usually TE is removed before CE. Also the usual reason to do chunked TE is if the sender does not know the size ahead of time and is streaming the output. But the MICE encoder cannot work streaming anyway since the blocks are processed in reverse.

**Comment by mnot** [comment]
It might make sense to align what packaging does with what we're discussing in https://github.com/httpwg/http-core/issues/165

**Comment by sleevi** [comment]
Considering that `kSecurityStateHeaders` are potentially state modifying in
the same way that cookies are, it seems they should also be prohibited.

**Comment by jyasskin** [comment]
@sleevi I'll split that decision out to #340 to avoid derailing this discussion.

**Comment by nyaxt** [comment]
From this thread + #340, I'm convinced that we should ban all headers in https://cs.chromium.org/chromium/src/net/http/http_response_headers.cc .

**Comment by jyasskin** [comment]
I'm hoping to delegate to the "don't cache these" list in https://github.com/httpwg/http-core/pull/181, which will take a bit longer to get into the HTTP draft.
