### ISSUE TITLE
Consider banning Strict-Transport-Security and Public-Key-Pins headers

### ISSUE THREAD

**Issue by jyasskin** [WICG/webpackage#340]
In https://github.com/WICG/webpackage/issues/336#issuecomment-439560219, @sleevi suggests that we add the contents of [`kSecurityStateHeaders`](https://cs.chromium.org/chromium/src/net/http/http_response_headers.cc?l=77) to https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#stateful-headers.

@sleevi, you're worried about attackers targeting sites that use a set of HSTS domains as an authentication cookie?

HTTP will define some set of headers that shared caches don't store, and I'd like to just blindly ban that list in signed exchanges, but I do see an argument to be a bit stricter in signed exchanges, since with signed exchanges the attacker doesn't have to be the first to visit the cache.

On the other hand, to be vulnerable to this attack, a site has to be using HSTS in a user-hostile way.

**Comment by jyasskin** [comment]
And, to be clear, the benefit of allowing `Strict-Transport-Security` in signed exchanges is that if we ban it, users can't bootstrap to HSTS before they're online, which increases the time they're vulnerable to network attackers.

**Comment by sleevi** [comment]
And the risk (in addition to the general risk of state modification via
SXG) is that someone can serve a maxAge=0 to unset it, undetectably, and
repeatedly for the lifetime of the signature.

**Comment by sleevi** [comment]
I don’t know if it matters much what sites do, compared to the cognitive
cost it would bring with reasoning.

For example, is maxAge relative to the first signature or the most recent
signature? If maxAge in SXG is <= what is served via TLS, then what is the
effective maxAge? If the client has a stored maxAge > the SXG maxAge, what
is the effective maxAge? Questions like this are all introduced by allowing
stateful side-effects.

Combine that with things like HSTS for subdomains, and could you use a
combination of SXG delivery to set a stateful identifier? That would be
dependent on whether SXGs (or bundles) could be delivered for subresources,
and how the browser handles subresources loads for HSTS. However, throw in
portals and it continues to get more confusing.

**Comment by davidben** [comment]
Consider also a site that deployed HSTS and then had to turn it off for whatever reason. Normally one can assume that, after maxAge + timeHeaderWasDisabled, the entry will have expired in all clients. That property relies on liveness from TLS.

**Comment by jyasskin** [comment]
I'm surprised that https://tools.ietf.org/html/rfc6797#section-6.1.1 says "The REQUIRED "max-age" directive specifies the number of seconds, after the reception of the STS header field, ..." instead of incorporating the initial-age calculation specified in https://httpwg.org/http-core/draft-ietf-httpbis-cache-latest.html#age.calculations.

Given that, I'm convinced by @davidben's point. (If the initial-age calculation were included, @sleevi's point would be more convincing. :smiley:)

**Comment by davidben** [comment]
I guess it's because HSTS is not really a property of the resource and really just connection metadata that we jam into HTTP responses because we have nothing better to do with it. :-) If you believe in that interepretation, then you would want the timer to start at the current time. Indeed if there's a site out there where no resource had been updated for years, all the age headers would be old and effectively disable HSTS.

Though I suspect the actual answer is this was an oversight. :-) Otherwise it'd probably have done a better job of marking it a hop-by-hop header and all that.
