### ISSUE TITLE
Clarify SXG + SW interactions

### ISSUE THREAD

**Issue by ithinkihaveacat** [WICG/webpackage#349]
The ["Navigations and subresources redirect" section of the Explainer](https://github.com/WICG/webpackage/blob/master/explainer.md#navigations-and-subresources-redirect) seems to suggest that once the SXG is unwrapped and the publishing URL is available, if the browser then discovers that a service worker is controlling the publishing URL, the request will be routed through the SW via the standard "fetch" event.

The SW then executes as normal with one exception: if the SW attempts a network request to the publishing URL (e.g. via `fetch()`), the browser will return the response stream embedded within the SXG instead of performing the network request. (That is, from the point of view of the browser, no network access will occur--the already-available response will be returned to the SW.)

It would be useful to know:

- Whether the various mechanisms that currently allow the SW to avoid the various browser caches (e.g. [cache = "no-store"](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache)) will be respected. (If not, this introduces an awkward difference in behavior.)
- Whether the response stream attached to the redirect will also be available via the [navigation.preload](https://developer.mozilla.org/en-US/docs/Web/API/NavigationPreloadManager) mechanism. (Also, was making the response available via this mechanism only considered? It seems a bit more compatible with what's actually going on, especially with respect to the time at which things occur.)

/cc @jakearchibald @twifkak

**Comment by jyasskin** [comment]
https://wicg.github.io/webpackage/loading.html#mp-http-network-or-cache-fetch should give a precise answer to your questions, but please let me know if it's the wrong answer. :)

**Comment by ithinkihaveacat** [comment]
That's perfect, thanks. (And sorry I missed it that section.)
