### ISSUE TITLE
Switch to binary format and more.

### ISSUE THREAD

**Issue by dimich-g** [WICG/webpackage#38]
Hi,

Capturing recent conversations with @jyasskin and @mrdewitt:

1. We think it makes sense to switch to 100% binary format since the header compression and parts body compression makes it mostly binary anyways. It also lets us to replace MIME boundary strings with direct chunk-size kind of encoding.
2. The Explainer and samples in it will be gradually updated to reflect switch to binary encoding. While in update, there can be some inconsistency in the doc.

Also discussed:
- Binary alignment at 32 bit boundaries (decided not to)
- Use Self-Delimiting Numeric Values (rfc 6256) (decided not to)
- Split content index and offset table (so the resources may be rearranged)
- Multiple hashes (to support deprecation of old ones)
- Cross-signing

**Comment by lrosenthol** [comment]
If you are moving to a binary format - why not use an existing one instead
of inventing yet another one?

**Comment by jyasskin** [comment]
@lrosenthol Which one?

**Comment by jyasskin** [comment]
[CBOR](http://cbor.io/) is an option for the package structure, and it even has a draft schema definition language, [CDDL](https://tools.ietf.org/html/draft-greevenbosch-appsawg-cbor-cddl-09). It won't be quite as compact as something we do custom, but it'll be easier to debug and to extend in the future.

**Comment by dimich-g** [comment]
CBOR looks interesting. It seems to support streaming on receiving end as well.

**Comment by lrosenthol** [comment]
CBOR does look interesting, but seems to be more focused on handling a
single file and not a package/collection of files & resources. I think we
need a more classic archiving format - something like a ZIP or StuffIt -
but with modern sensibilities.  I'll do some research

**Comment by dimich-g** [comment]
There are 2 orthogonal things - binary encoding and then an index/manifest/hashing structure.  Formats like CBOR provide the former w/o attempting to provide the latter. So if we want specific structure and content of the package metadata (index, manifest, certificates and hashes), and don't care much about the way to assemble those pieces into a binary file with chunks of certain size is not important.

The main issue with Zip and other archiving formats is they mostly were developed without streaming on receiving and with fixed and/or limited set of metadata, and they will have to be 'augmented' in one way or another.

CBOR seems to be a simple way to assemble length-prefixed and variable-length records, arrays and maps, and supports variable-length numbers, byte blobs and UTF-8 strings. No notion of a directory or hashing, which seems to be a good thing since those are exactly the subject of this proposal.

**Comment by mrdewitt** [comment]
It is small potatoes, but CBOR has already got debug tools and pretty
printers, so we'd have a head start on tooling as well.

**Comment by jyasskin** [comment]
Fixed by #36.
