### ISSUE TITLE
dump-signedexchange: make validation success/failure more obvious

### ISSUE THREAD

**Issue by ithinkihaveacat** [WICG/webpackage#389]
The `dump-signedexchange` tool's `-verify` option sort of hides the validation result in the middle of its output. It would be useful if this were more prominently reported, especially in the failure case. Not a crucial thing, but it's not immediately obvious that validation has failed.

Screenshot of successful validation:

<img width="922" alt="screenshot 2019-02-03 at 22 07 59" src="https://user-images.githubusercontent.com/51244/52183540-9b2c6600-2800-11e9-96e2-00948b7648f4.png">

Screenshot of unsuccessful validation:

<img width="922" alt="screenshot 2019-02-03 at 22 08 23" src="https://user-images.githubusercontent.com/51244/52183543-a2ec0a80-2800-11e9-99fd-6c8e4138f339.png">

**Comment by irori** [comment]
Thanks for filing this! Created #398.
