### ISSUE TITLE
Figure out unsigned sub-packages

### ISSUE THREAD

**Issue by jyasskin** [WICG/webpackage#39]
From @dimich-g's https://github.com/dimich-g/webpackage/pull/36#issuecomment-290316360:

Without a signed manifest, there's no structure to identify sub-packages.

However, it might just work to lump all the resources together at the top level. Do we need to identify the sub-package structure?

**Comment by bmeck** [comment]
Can you clarify

> lump all the resources together at the top level

Sub-packages are certainly distinct, even if unsigned.

**Comment by jyasskin** [comment]
Sorry for my delay in replying. If a package consists of a bunch of resources, and a sub-package consists of a bunch of resources with distinct URLs, do we need to have the packaging format distinguish the sub-package's resources from the main package's resources? How would a package consumer use that information?

**Comment by jyasskin** [comment]
We don't have subpackages anymore.
