### ISSUE TITLE
Add an example SXG error report

### ISSUE THREAD

**Issue by jyasskin** [WICG/webpackage#400]
@horo-t, could you add an example ([`<div class="example" id="example-network-error-log">`](https://tabatkins.github.io/bikeshed/#notes-etc)) Network Error Log that could be produced by the spec you added in #374? https://wicg.github.io/webpackage/loading.html#queue-report would be a reasonable place to put it unless you think somewhere else will be more clear.

**Comment by horo-t** [comment]
Sure.
