### ISSUE TITLE
Are OCSP responses with multiple SingleResponses allowed?

### ISSUE THREAD

**Issue by twifkak** [WICG/webpackage#405]
https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#cross-origin-trust item 7.3 says:

> Validate that `main-certificate` has an `ocsp` property
> ({{cert-chain-format}}) with a valid OCSP response whose lifetime
> (`nextUpdate - thisUpdate`) is less than 7 days ({{!RFC6960}}).

But per https://tools.ietf.org/html/rfc6960#section-4.2, an `OCSPResponse` may have multiple `SingleResponse`s, each with its own `nextUpdate` and `thisUpdate`. Are such OCSP responses disallowed by the spec? Otherwise, to which `SingleResponse` does this requirement apply?

**Comment by sleevi** [comment]
> Are such OCSP responses disallowed by the spec?

Not at present. Considering the implications to CAs, that would start getting into a policy/certificate profile doc beyond just the extension. Both 6960 and 5019 permit multiple `SingleResponse`s.

> Otherwise, to which SingleResponse does this requirement apply?

Consistent with the existing handling of OCSP and RFC 5019/5280/6960, provided that there is a `SingleResponse` that meets this criteria, one may consider the `OCSPResponse` valid for that certificate.

**Comment by twifkak** [comment]
Ah, OK, thanks for the clarification. Do you think it's worth clarifying that in the spec text, or is the implicit consistency sufficient?

**Comment by sleevi** [comment]
That's a good question! If @jyasskin is OK with adding more text, I don't think there's fundamental harm in specifying/clarifying. I think we'd want feedback from other UAs - I don't believe this would present any challenges for Mozilla, but for Apple/Microsoft, their OCSP stacks are maintained by different teams, and they may have spec language feedback and/or want to leave it opaque/implicit (as it is in TLS and RFC 5280)

**Comment by jyasskin** [comment]
I don't really want this specification to be in the business of defining how we interpret OCSP responses. The SingleResponse specifies a certID, and duplicates of those could be inconsistent in all sorts of ways that we don't call out. Let's just stay with the language used by other specs in this area. For example, https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.6.3.pdf section 4.9.10 just says, "OCSP responses from this service MUST have a maximum expiration time of ten days."

**Comment by twifkak** [comment]
OK, closing then.
