### ISSUE TITLE
option to output JSON from dump-signedexchange

### ISSUE THREAD

**Issue by patrickkettner** [WICG/webpackage#418]
Hi there!
I was helping @ithinkihaveacat with some SXG tooling, and were wondering if y'all would accept a PR that would cause `dump-signedexchange` to output JSON rather than its current format (via a flag perhaps?) to help the data be easier to export. Wanted to confirm before I dive into the go code, however

**Comment by patrickkettner** [comment]
(cc @irori)

**Comment by nyaxt** [comment]
The plan SGTM
