### ISSUE TITLE
Update examples for CBOR format

### ISSUE THREAD

**Issue by jyasskin** [WICG/webpackage#42]
https://github.com/dimich-g/webpackage#use-cases has lots of examples that use an old version of the design.

**Comment by BigBlueHat** [comment]
@jyasskin is there a place to get visibility into the move to CBOR? The MIME-like packaging format described in the original [web-packaging](https://www.w3.org/TR/web-packaging/) spec felt very familiar and comfortable. :smiley: Mostly curious as to the choices made.

Thanks! :tophat:

**Comment by jyasskin** [comment]
#10 and #38 discuss the decision to move to a binary format. We also got feedback that it was hard to reliably generate the MIME boundary strings that the TAG's format needed, and that length prefixing was easier.

**Comment by BigBlueHat** [comment]
@jyasskin much thanks for the description and the links! CBOR does look promising. Cheers!
