### ISSUE TITLE
Content-Type version identifier, should it be case-sensitive?

### ISSUE THREAD

**Issue by Gregable** [WICG/webpackage#435]
For a server returning a signed exchange, the content type will be something like:

```
content-type: application/signed-exchange;v=b3
```

As per https://www.w3.org/Protocols/rfc1341/4_Content-Type.html, the `application/signed-exchange` and `v` parts of this are case-insensitive, whereas the `b3` part (parameter value) is not well defined in the RFC:

> Parameter values are normally case sensitive, but certain parameters are interpreted to be case- insensitive, depending on the intended use.

I don't see anything explicit in the Signed Exchange spec about the case-sensitivity of the parameter value. Should we call this out explicitly?

It's a small point, but I would also suggest that it seems a little error-prone to have this entire string be case-insensitive except for one character (the `b`). Perhaps we should define the version identifier to also be case-insensitive for consistency. Thoughts?

**Comment by jyasskin** [comment]
The Signed Exchange spec does give an ABNF for the parameter value of `DIGIT/%x61-7A` (should be `1*(DIGIT/%x61-7A)`), i.e. only lowercase ASCII letters.

I'm not certain that's the right behavior, but I'm inclined to keep it since it limits unnecessary variation in server behavior.
