### ISSUE TITLE
bundle tool install error

### ISSUE THREAD

**Issue by dauwhe** [WICG/webpackage#438]
The signedexchange tools installed easily, but I get an error trying to install the bundle tools: 

```
$ go get -u github.com/WICG/webpackage/go/bundle/cmd/...
package github.com/influxdata/influxdb/client/v2: cannot find package "github.com/influxdata/influxdb/client/v2" in any of:
	/usr/local/go/src/github.com/influxdata/influxdb/client/v2 (from $GOROOT)
	/Users/cramerd/go/src/github.com/influxdata/influxdb/client/v2 (from $GOPATH)

```
Going to https://github.com/influxdata/influxdb finds:

> If you are looking for the InfluxDB 1.x Go Client, we've created a new [repo](https://github.com/influxdata/influxdb1-client) for that.

**Comment by irori** [comment]
Thanks. https://github.com/mrichman/hargo/pull/12 should fix this.

**Comment by dauwhe** [comment]
It works! Thanks!
