### ISSUE TITLE
dump-signedexchange: command not found

### ISSUE THREAD

**Issue by prash-mi** [WICG/webpackage#441]
I am trying to install 'dump-signedexchange' on Linux (Debian) and Mac(v10.14) running go 1.12.5, using this command:

`go get -u github.com/WICG/webpackage/go/signedexchange/cmd/...`

but its simply exiting with no output on the console: 

```
$ go get -u github.com/WICG/webpackage/go/signedexchange/cmd/...
$ dump-signedexchange
bash: dump-signedexchange: command not found
```

Is there an alternate way to install it?

**Comment by hajimehoshi** [comment]
`go get` installs the binaries at `$HOME/go/bin` by default :)

**Comment by prash-mi** [comment]
Thanks @hajimehoshi . (Somehow I was expecting the binary to be available in the $PATH, my bad!)

One follow-up, would you know how to use `-verify` with `dump-signedexchange`, the following command is not returning:
`
./dump-signedexchange -verify https://staging.example.com 
 `

I want to verify signed exchange on a staging server

**Comment by irori** [comment]
`dump-signedexchange` is not returning because it's waiting for SXG input from stdin. The following command pipe would do the work:
```
curl https://staging.example.com | dump-signedexchange -verify
```

Once https://github.com/WICG/webpackage/pull/429/ is merged, `dump-signedexchange` will accept the `-uri` flag:
```
./dump-signedexchange -verify -uri https://staging.example.com
```

**Comment by prash-mi** [comment]
Thanks for the update @irori . One followp, I tried this command with a couple of URLs with and without signexchange implemented and got the same response, here is the output:

This URI has SGX enabled on prod: 
`curl -si -H 'amp-cache-transform: google' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' https://www.oyorooms.com/hotels-in-delhi/ | dump-signedexchange -verify`
Output:
`2019/06/14 14:19:25 singedexchange: unknown magic bytes: [72 84 84 80 47 50 32 50]`

This URI is not having SGX enabled: 
`curl -si -H 'amp-cache-transform: google' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' https://mweb-demos.appspot.com | dump-signedexchange -verify`
Output:
`2019/06/14 14:21:31 singedexchange: unknown magic bytes: [72 84 84 80 47 50 32 50]`

Can you please let me know that what output is expected when SGX is enabled ?

**Comment by irori** [comment]
Curl's `-i` option outputs HTTP response headers to the stdout, so `dump-signedexchange` tries to parse it as SXG format (`[72,84,84,80,47,50,32,50]` == "HTTP/2 2" in ASCII).

Now https://github.com/WICG/webpackage/pull/429 is merged, you can use `dump-signedexchange` with the `-uri` flag:

```
$ dump-signedexchange -requestHeader 'amp-cache-transform: google' -uri https://www.oyorooms.com/hotels-in-delhi/ -verify -payload=false

format version: 1b3
request:
  method: GET
  uri: https://www.oyorooms.com/hotels-in-delhi/
  headers:
response:
  status: 200
  headers:
    Content-Encoding: mi-sha256-03
...
```

**Comment by irori** [comment]
Closing, but feel free to add comments if you have further questions.
