### ISSUE TITLE
Can the manifest section be optional?

### ISSUE THREAD

**Issue by irori** [WICG/webpackage#499]
Currently Bundled Exchanges [must have a `manifest` section](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html#load-metadata). It was reasonable in the past because its `start_url` could be used to indicate the default resource in the bundle, but we now have the [primary URL](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html#semantics-load-metadata) which is meant to be the bundle's main resource URL.

Also, in some use cases (for example [Save and share a web page](https://wicg.github.io/webpackage/draft-yasskin-webpackage-use-cases.html#snapshot)) manifest may not be available.

**Comment by jyasskin** [comment]
I think it's a good idea to make the manifest optional, since the only field we actually need from the manifest is the `start_url`.

**Comment by jyasskin** [comment]
Fixed by #505.
