### ISSUE TITLE
WebBundle for sub-resources

### ISSUE THREAD

**Issue by Jxck** [WICG/webpackage#526]
Current Spec seems based on top level url(html) + subresouces.
but I think it can use for bundling subresource like JS modules.

in current real world, JS modules are depends on tiny modules in npm.
if you write correct import maps and serve node_modules directory on server will solve dependencies
on the browser.

but npm modules are so tiny (substack way), so there cause tons of fetch likely over 100.
and Chrome Team reports this will cause IPC bottle neck.

https://docs.google.com/document/d/1ds9EEkcDGnt-iR8SAN-_7nsOfw7gsMfhZjzZ_QAIyjM/edit

finally they recommend to use webpack and make them in single bundle.js. and developers doing that.

this means we don't use ES modules directory, even if spec has done, and impl has almost done in browser. `import` notation is only a keyword for webpack, and `<script type=text/javascript src=bundle.js>`. too sad to see them.

if we can use WebBundles for bundling npm modules and fetch them in one time.
and also browser extract and handle them as if they are fetched each-by-each.
browser can cache as separated req/res pare, we can use them via `import`.

webbundle for subresources are also fine for WebFont(multi weight), CSS Sprite(bundle images), Favicon(apple-touch-icon, favicon.ico etc).

so I believe webbundle will change our web content deployment.

**Comment by jyasskin** [comment]
I think this issue is fixed by #565, which documents that we think it's an important use case to solve.
