### ISSUE TITLE
<base href="/" /> breaks request URLs from web bundle

### ISSUE THREAD

**Issue by lacolaco** [WICG/webpackage#531]
`go/bundle` cannot make a valid bundle for HTML which includes `<base href="/" />`. In the case, `.wbn` file will be actually created but HTTP requests from the document are broken. These URLs start with `file://` schema. 

![image](https://user-images.githubusercontent.com/1529180/68654082-0cace980-04e2-11ea-9ce4-3f80c8528ace.png)

**Comment by horo-t** [comment]
This is an issue of Chromium's experimental implementation.
Could you please file a bug in https://crbug.com ?

**Comment by lacolaco** [comment]
@horo-t I've filed. https://bugs.chromium.org/p/chromium/issues/detail?id=1023929

**Comment by horo-t** [comment]
Thank you.
Closing this issue.
