### ISSUE TITLE
Add display mode for web bundles

### ISSUE THREAD

**Issue by AshleyScirra** [WICG/webpackage#533]
It might be interesting to support other display modes in web bundles, e.g. "standalone", much like the manifest can set for PWAs.

Then you could end up in the situation where you have a .wbn file you double click and it runs in an app-like window without the browser address bar - much like an Electron/NW.js app, but actually running in the browser.

**Comment by jyasskin** [comment]
Bundles have a ["manifest" section](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html#manifest-section) which is intended to point to an App Manifest, which in turn can set the [display mode](https://www.w3.org/TR/appmanifest/#display-member). So I think this is already done and am closing the issue, but feel free to reopen with more explanation of what's missing. 🙂
