### ISSUE TITLE
Example not working for me

### ISSUE THREAD

**Issue by kohlerm** [WICG/webpackage#535]
The preact-todomvc example at https://web.dev/web-bundles/ 
does not work for me. 
I get an error at the end. 

../go/bin/gen-bundle -dir build -baseURL https://preact-todom.vc -primaryURL https://preact-todom.vc -o todomvc.wbn
2019/11/17 15:58:06 Creating exchange: build -> https://preact-todom.vc/
2019/11/17 15:58:06 Creating exchange: build/app.js -> https://preact-todom.vc/app.js
2019/11/17 15:58:06 Creating exchange: build/index.html -> https://preact-todom.vc/index.html
2019/11/17 15:58:06 Creating exchange: build/todomvc-common/base.css -> https://preact-todom.vc/todomvc-common/base.css
2019/11/17 15:58:06 Creating exchange: build/todomvc-common/base.js -> https://preact-todom.vc/todomvc-common/base.js
2019/11/17 15:58:06 Creating exchange: build/todomvc.css -> https://preact-todom.vc/todomvc.css
2019/11/17 15:58:06 Failed to write exchange. err: bundle: No exchange for primary URL https://preact-todom.vc

**Comment by irori** [comment]
Thank you for trying it out.

There was an error in the command line. The correct command is:
```
./go/bin/gen-bundle -dir build -baseURL https://preact-todom.vc/ -primaryURL https://preact-todom.vc/ -o todomvc.wbn
```
(note the trailing '/' in the URLs)

The web.dev article is already [fixed](https://github.com/GoogleChrome/web.dev/pull/1888).
