### ISSUE TITLE
Chrome refuses to load generated bundles

### ISSUE THREAD

**Issue by mgissing** [WICG/webpackage#568]
I have been trying to create my own web bundles (with both gen-bundle and the JS encoder)
and I noticed that sometimes Chrome (both 80 release and 83.0.4102.0 Win x64) rejects the bundle with ERR_INVALID_WEBBUNDLE (no further info in console or devtools)

After fiddling with it a bit, it seems that Chrome is very picky about the order the exchanges appear in.
I am sure that its not the content, since it is reproducible with just changing a single file name.
If I sort the result URLs first by length and then lexically everything works fine.

Not sure if this is the right location to report this since it might be Chromium related - but if anyone is interested I can provide more details and a minimal example

**Comment by irori** [comment]
The [`index` section](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html#name-parsing-the-index-section) must be a deterministically encoded CBOR map, which means its entries must be sorted. The order of responses in the `responses` section is arbitrary.

Would you file a Chromium bug (with example `.wbn` if possible) from http://crbug.com/new with `Blink>Loader>WebPackaging` component? Chromium should at least output detailed error message in console.

Thanks!

**Comment by mgissing** [comment]
Filed chromium issue https://bugs.chromium.org/p/chromium/issues/detail?id=1068481
After looking a bit further into issue it seems that both the JS encoder and the gen-bundle get the sort order wrong. 
Both go "bytes.compare(..)" and Buffer.compare() in node do not sort by length but only by byte values.

https://github.com/WICG/webpackage/blob/7412e313f959808ed927cfd4156acffb8bbd9420/go/signedexchange/cbor/encoder.go#L228

**Comment by irori** [comment]
`encoder.go` sorts map keys by CBOR-encoded bytes of keys, i.e. "z" (encoded as `61 7A`) comes before "aa" (encoded as `62 61 61`). See the unit test of the encoder:

https://github.com/WICG/webpackage/blob/7412e313f959808ed927cfd4156acffb8bbd9420/go/signedexchange/cbor/encoder_test.go#L188

Effectively it sorts keys by length and then by value.

How did you create your bundle file? Was it created by `gen-bundle`, the `wbn` JS library, or any other tool?

**Comment by mgissing** [comment]
Sorry I missed the part were the sort includes the length prefix - thats fine.
I have written my own encoder on top of CBOR and with sorting that works fine now.

Regarding gen-bundle - maybe I'm using it wrong:
This is the file structure:

```
DummyPage/index.html
          test.jpg
          unused.jpg
          unused2.jpg
```

This doesnt work:
`gen-bundle -baseURL http://example.org/ -primaryURL http://example.org/index.html -dir  DummyPage -o notworking.wbn`

This does:
`gen-bundle -baseURL http://example.org/ -primaryURL http://example.org/ -dir  DummyPage -o working.wbn`

[bundle-working-dump.txt](https://github.com/WICG/webpackage/files/4449270/bundle-working-dump.txt)
[bundle-notworking-dump.txt](https://github.com/WICG/webpackage/files/4449271/bundle-notworking-dump.txt)

Also I was wondering if  "Content-Encoding: gzip" in responses is supposed to work in Chrome right now - currently Chrome seems to ignore that

**Comment by irori** [comment]
For `index.html`, `gen-bundle` generates a redirect (301) resposnse to `./` (as you can see in [bundle-notworking-dump.txt](https://github.com/WICG/webpackage/files/4449271/bundle-notworking-dump.txt)). But currently Chromium cannot handle it. This is tracked at https://crbug.com/1040831.

We'd like to support `Content-Encoding: gzip` in bundled respohnses in the future, but it doesn't work currently. This is tracked at https://crbug.com/1063738.

I think this WICG/webpackage issue can be closed. Please watch the Chromium issues for progress.
