### ISSUE TITLE
Question about compressed content

### ISSUE THREAD

**Issue by mgissing** [WICG/webpackage#569]
Is it an intended use case to allow "Content-Encoding: gzip" or similar in the the web bundle and have a compressed body?
I know you could zip the whole bundle but for passing it around as a compact file it would really be useful

**Comment by jyasskin** [comment]
Yes. https://wicg.github.io/webpackage/draft-yasskin-wpack-use-cases.html#name-compress-stored-packages says this indirectly.

**Comment by jimmywarting** [comment]
Hmm, i had the same question but didn't feel like this answered my question...
i'm trying to generate a webbundle that have gzip'ed body

(i'm not gziping the hole web bundle (only the body) and adding
```
'content-type': 'text/html',
'content-encoding': 'gzip',
'content-length': length
```
but it all return gibberish `‹íÂ  ´‡ñþdŠ¹ªªº±bËnñ`

I'm missing some accept-encoding or something?
Do anyone have a sample bundle that has compressed body that i could take a look at and dump to inspect its content?

**Comment by milahu** [comment]
> for passing it around as a compact file

see also [tiddlywiki](https://github.com/Jermolene/TiddlyWiki5)

what does work is inlining the gzip data as base64 in an hidden element

```html
<pre style="display:none" id="packfile">
UEFDSwAAAAIAABQFkw14nJXLQQrDIBBA0b2nmH2hjHU0DpTSZTc9hI5jE4hJCOb+TY/Q5fvw+64K
EaUKsi9RBsbgfYxUQrmJkji1pNlFSTWbLe26dFCnjvKtMglqKox+COjQWqrM2eZK7BAxm3T0cd3h
Pc1pgddPcG8nxuP5aWmar7K2B9gQ2CIjE1zQIpqztql3/f80x2a+AzI+TZ4NeJyNy0EKwjAQheF9
TpG9VGaStM6AiEs3HmKaTGzBtKWk9zeCB3D5P95Xd1XrUxzJkyoTSgJOpOQ1955i1qgQcuaRM5tN
...
</pre>
```

and then decompress with [DecompressionStream](https://developer.mozilla.org/en-US/docs/Web/API/DecompressionStream) in chrome or [tiny-inflate](https://github.com/foliojs/tiny-inflate) in firefox

```js
var packfile = document.querySelector("#packfile").innerHTML
packfile = atob(packfile);
packfile = inflate(packfile);
```

**Comment by jimmywarting** [comment]
base64 would not save such a much space... would rather save something like
`/style.css.gz` as a separate response, fetch it manually or install some service worker interceptor. and then use DecompressionStream
