### ISSUE TITLE
Figure out how to identify signing algorithms

### ISSUE THREAD

**Issue by jyasskin** [WICG/webpackage#58]
Options:
1. [TLS 1.3 SignatureScheme](https://tlswg.github.io/tls13-spec/#rfc.section.4.2.3) codes.
2. <strike>[JWS algorithm names](https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms).</strike> (I have advice to avoid these.)
3. RFC5280's [AlgorithmIdentifier](https://tools.ietf.org/html/rfc5280#section-4.1.1.2) used in certificates.
4. Define a mapping from the certificate's public key to a signature algorithm. This is easy for ECDSA and EdDSA keys, but would need work for RSA keys. Straw man: <=3072 bits gets rsa_pss_sha256, and >=3073 gets rsa_pss_sha384.

In some cases, like TLS' [ecdsa_secp256r1_sha256](https://tlswg.github.io/tls13-spec/#rfc.section.4.2.3) vs JWS' [ES256](https://tools.ietf.org/html/rfc7518#section-3.4), even though the algorithm is the same, the signature appears in different formats.

Any of these options is sufficient to let us sign with any TLS certificate, but TLS doesn't yet have identifiers for post-quantum signature schemes that counter-signatures might want to use.

**Comment by jyasskin** [comment]
Crypto folks seem to strongly prefer Option 4.

**Comment by lrosenthol** [comment]
How would you use a TLS cert to sign "code" or content, which is what you
doing here?  It's not really what a TLS cert is supposed to be used for.
It would also bind things to the domain and not necessary to the
author/producer/publisher of the content.

**Comment by jyasskin** [comment]
For "how", see https://github.com/dimich-g/webpackage#manifest-signatures, which needs to be updated with the result of this issue.

From talking to some security folks, it looks like it'll be safe enough to sign with a TLS cert if we also check for revocation and urgent package updates periodically. e.g. every 7 days would definitely be sufficient. I need to flesh that out in the explainer.

Yes, getting package content to be same-origin with a domain needs the signature to bind the content to the domain. It'll be possible to also counter-sign with extra certificates that might be attached to a real-world identity instead of a domain, and that's one reason I'm worried about certificate types that aren't supported by TLS.

**Comment by lrosenthol** [comment]
And for the specific use cases for web packages that you have today, I can
see that being sufficient.

But as we move things like PWP forward, it's not helpful there - as that
content isn't bound to a domain, at least not by the author.  It could
potentially be by a publisher, but then that limits the usefulness.
