### ISSUE TITLE
OID for signed certificate timestamp

### ISSUE THREAD

**Issue by iesiyok** [WICG/webpackage#613]
Hello,

I think the SCT code given in 
```
openssl x509 -req -days 90 -in cert.csr -signkey priv.key -out cert.pem \
  -extfile <(echo -e "1.3.6.1.4.1.11129.2.1.22 = ASN1:NULL\nsubjectAltName=DNS:example.org")
```
is wrong. That's why gen-certurl throws "Warning: Neither cert nor OCSP have embedded SCT list. Use -sctDir flag to add SCT from files." for my case.
I think the OID code should be "1.3.6.1.4.1.11129.2.4.2"
http://oid-info.com/cgi-bin/display?oid=1.3.6.1.4.1.11129.2.4.2&a=display

**Comment by sleevi** [comment]
That’s not the OID for SCTs, which cannot be embedded for self-signed certs. It’s the OID for the `CanSignHttpExchanges` extension, which is listed in the comment on the line immediately preceding in the README.

**Comment by jyasskin** [comment]
Feel free to reopen if something still turns out to be wrong in the docs.
