### ISSUE TITLE
Subresource loading: Add a section to explain how resource-bundles are related.

### ISSUE THREAD

**Issue by hayatoito** [WICG/webpackage#630]
We should spell out how "Subresource loading with Web Bundles" are related to [WICG/resource-bundles](https://github.com/WICG/resource-bundles/) in its [explainer](https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading.md).

The context: https://github.com/w3ctag/design-reviews/issues/616#issuecomment-790395734

**Comment by jyasskin** [comment]
We should also update the [alternate designs](https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading.md#alternate-designs) with some of the ideas from [resource-bundles](https://github.com/WICG/resource-bundles/blob/main/subresource-loading.md#example) and [MT's post](https://lowentropy.net/posts/bundles/#indirection-for-identifiers)

**Comment by hayatoito** [comment]
A good point. Some of alternative designs have not been updated, and I'm feeling a bit outdated.
We should collect alternative designs and summarize them in the explainer.

**Comment by hayatoito** [comment]
[Issue Triage]
Let me close this tentatively.
