### ISSUE TITLE
Cite ESCAPE Workshop paper in the Archival use case section

### ISSUE THREAD

**Issue by ibnesayeed** [WICG/webpackage#649]
Currently, the Archival section cites an early tweet showing interest in web bundles. However, a paper explored the idea of [Supporting Web Archiving via Web Packaging](https://arxiv.org/abs/1906.07104) in the ESCAPE workshop in more details. I think a reference to that document will be more useful as the Archival section is rather brief in the document.

**Comment by hayatoito** [comment]
[Issue Triage]
Thanks for sharing the info.

Probably we can discuss this in the upstream repository, https://github.com/wpack-wg/bundled-responses/issues/19, which now defines the format.
