### ISSUE TITLE
Consider using a more specific scheme for opaque origin

### ISSUE THREAD

**Issue by hayatoito** [WICG/webpackage#650]
Regarding [Support opaque origin iframes](https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading-opaque-origin-iframes.md), we might want to use a new scheme, instead of `urn:uuid`.

@jyasskin I remember you mentioned that we should introduce a new scheme, but I couldn't find. It would be appreciated if you can share the context!

Note this is tracked as a  v1 issue in #648.

**Comment by irori** [comment]
> @jyasskin I remember you mentioned that we should introduce a new scheme, but I couldn't find. It would be appreciated if you can share the context!

I think it was https://github.com/WICG/webpackage/pull/629#pullrequestreview-603306066.
