### ISSUE TITLE
Updating the signature 

### ISSUE THREAD

**Issue by iesiyok** [WICG/webpackage#655]
Sorry if this was asked before, I couldn't find in the issues.

I am trying to update Signature by following the Section 3.6 https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#name-updating-signature-validity

For example, if I have a signature like below:

`sxg1-b3,https://example.org/test_2/index.htmlm?label;cert-sha256=*+uu3gDE..IZUbQ8uzhaFCvu7IoiLs=*;cert-url="https://example.org/cert/cert.cbor";date=1621198535;expires=1621198835;integrity="digest/mi-sha256-03";sig=*MEQ..t3AK+JhXtX4Tx1ABK7rAiB99CQFsPVyvTSvfI3X7LinjwRGP7LLye0V+hMqiZqHFQ==*;validity-url="https://example.org/test_2/resource.validity.1621198535"?FdigestX9mi-sha256-03=aIKBy8..XKEFIIhrogAPg=G:statusC200Lcontent-typeXtext/html; charset=utf-8Pcontent-encodingLmi-sha256-03{
  "url": "https://example/test_2/index.html",
  "name": ""
}`

and I want to update it by providing the data below in the resource.validity.1621198535 file :

`{
  "signatures": [
    'sig1; '
    'sig=*MEUCIDTKptce...oBy5bi7DlAiEAkSxXCBNeyv4HjHMNeC4KwQeR2Ki4LAW/KfA6yOoPh/8=*; '
    'validity-url="https://example.org/test_2/resource.validity.1621198655"; '
    'integrity="digest/mi-sha256-03"; '
    'cert-url="https://example.org/cert/cert.cbor"; '
    'cert-sha256=*+uu3gDE..IZUbQ8uzhaFCvu7IoiLs=*; '
    'date=1621198655; expires=1621199803'
  ]
}`

Using the Chrome browser, I cannot observe whether the Chrome is attempting to update the signature. It shows the same error messages 

`Invalid timestamp. creation_time: 1621198535, expires_time: 1621198835, verification_time: 1621199048
index.html:1 Failed to verify the signed exchange header.
index.html:4 GET https://example.org/test_2/index.sxg net::ERR_INVALID_SIGNED_EXCHANGE 200 (OK)`

Am I doing anything wrong?

**Comment by horo-t** [comment]
Sorry, we haven't the logic in Chromium.
Filed https://crbug.com/1210821
