### ISSUE TITLE
Consider dropping the version

### ISSUE THREAD

**Issue by martinthomson** [WICG/webpackage#658]
Looking at IETF 111 slides, I see that there is a magic field and a version field.  Magic is perhaps useful (though redundant with content-type in some contexts), but version is strictly redundant.  The way we have managed this in other contexts is to change the magic (or content-type) as the format evolves, with a final string being reserved for eventual publication.  As the only response (now) is to reject a bundle if the version doesn't match, this is achieved adequately by a change in magic.

**Comment by hayatoito** [comment]
Let me close this issue, in favor of the upstream issue:
https://github.com/wpack-wg/bundled-responses/issues/19
