### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by irori** [WICG/webpackage#660]
https://github.com/WICG/webpackage/pull/659 is blocked by CI not working.

https://travis-ci.org/github/WICG/webpackage/builds/ says:

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

I think there are two options:

- [Migrate](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) to travis-ci.com. Probably it needs repository admin's power (@jyasskin)
- Switch from Travis-CI to GitHub workflows. I see some other WICG repositories recently switched to GH workflows ([link](https://github.com/search?o=desc&q=org%3AWICG+travis&s=committer-date&type=Commits)), though I'm not sure whether there's strong reason to do that.

**Comment by hayatoito** [comment]
Thanks for investigating!

It seems a short term solution is to migrate to travis-ci.com, however, I guess we want to switch to GH workflows eventually anyway. 
Let me investigate how feasible it is.

**Comment by jyasskin** [comment]
Thanks for migrating to GH workflows. Travis-ci.com requires extra permissions to write to repositories, so it's not really viable. I've deleted the webhook for travis-ci.org, so it should stop trying to build PRs.

**Comment by irori** [comment]
> I've deleted the webhook for travis-ci.org, so it should stop trying to build PRs.

Hmm, `continuous-integration/travis-ci` was still triggered in https://github.com/WICG/webpackage/pull/662.

**Comment by hayatoito** [comment]
I've also removed `Travis CI` from this repository's Settings > Branches > Branch protection rules.

In #662, 
> ipr — PR has contribution issues. The following users' affiliation could not be determined

It seems this is unrelated to travis CI, I think.
This repository has another webhook, `https://labs.w3.org/repo-manager/api/hook`. I guess this is used for IPR check.

**Comment by irori** [comment]
Thanks! Travis CI did not run against the last push in #662.
