### ISSUE TITLE
Use <script> tag, instead of <link> tag

### ISSUE THREAD

**Issue by hayatoito** [WICG/webpackage#670]
This is a tracker to replace `<link>` tag with `<script>` tag in [subresource loading](https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading.md).

Our action items would be:

1. Define a syntax such as:

```html
<script type=webbundle>
    {
        "source": "foo.wbn",
        "scopes": ["js"],
        "resources": ["css/a.css", "css/b.css"]
    }
</script>
```

  The syntax (json's scheme) should be *compatible* to a syntax used in [BundlePreloading](https://github.com/WICG/resource-bundles). We don't want to have two kinds of `<script type=>` elements for a webbundle.

2. Consider the semantic difference between `<link>` elements and `<script>` elements, and re-consider the features which can be supported in `<script>` tag. `<script>` tag can have more restrictions.

----

Chromium is starting to prototype to use `<script>` tag here ([CL](https://chromium-review.googlesource.com/c/chromium/src/+/3128843/)).
We'll share our feedback in this thread once we have more insights using `<script>` tag via prototyping.

This issue is one of the blockers to ship MVP, tracked in https://github.com/WICG/webpackage/issues/648.

**Comment by hayatoito** [comment]
FYI. We are starting to update the explainer. https://github.com/WICG/webpackage/commit/725c28cc080c17aa679f18eb23d4a4fbdb636cd6

There are still remaining issues for `<script>`-based API. Let's use this issue for further discussion.

**Comment by uasan** [comment]
Does this mean that the download of the bundle will start no earlier than the parsing of the HTML document, and It is impossible to use [HTTP preload link headers with a description of the webbundle](https://github.com/WICG/webpackage/issues/657)?

**Comment by hayatoito** [comment]
That's true. That's a cons of using `<script>`-based API, which is no longer able to support HTTP Header link automatically.

**Comment by hayatoito** [comment]
[Issue Triage]
It seems we can close this issue. The spec is now using `<script>` tag.
