### ISSUE TITLE
Current support

### ISSUE THREAD

**Issue by bitdivine** [WICG/webpackage#671]
Hello,

Do I understand correctly that it is currently not possible to serve a website as a web bundle?

Chrome status indicates that navigation to bundles is in development: https://www.chromestatus.com/features/5377722941440000

I made a small test case, putting a couple of files in a signed web bundle, served it and the bundle was downloaded as a file, not loaded as a page.

I repeated the same, wrapping the signed wbn in sxg.  Again, the wbn was downloaded as a file, not loaded as a page.  (demo: 
 https://demteam.org/html/edge.html  )

Many thanks, Max

In case it should work, but I am doing something wrong, these are the commands I am using:
```
max@swift:~/projects/sxg-demo/v6 (0)$ cat ./bin/4.1-mkbundle
gen-bundle -dir www -baseURL https://winning.black/ -o www.wbn -primaryURL https://winning.black/

max@swift:~/projects/sxg-demo/v6 (0)$ cat ./bin/4.2-sign-bundle 
sign-bundle \
  -i www.wbn \
  -certificate cert.cbor \
  -date "$(date +%Y-%m-%dT%H:%M:%SZ -d "24 hours ago")" \
  -expire 72h \
  -privateKey myOrigin.key \
  -validityUrl https://winning.black/resource.validity.msg \
  -o www-signed.wbn

max@swift:~/projects/sxg-demo/v6 (0)$ cat ./bin/4.3.wrap-bundle-in-sxg
set -eux
gen-signedexchange \
  -date "$(date +%Y-%m-%dT%H:%M:%SZ -d "24 hours ago")" \
  -expire 72h \
  -uri https://winning.black/hello.wbn \
  -content www-signed.wbn \
  -responseHeader "Content-Type: application/webbundle" \
  -certificate myOrigin-chain.pem \
  -privateKey myOrigin.key \
  -certUrl https://demteam.org/cert/cert.cbor \
  -validityUrl https://winning.black/resource.validity.msg \
  -o winning.black.bundle.sxg
```

**Comment by hayatoito** [comment]
Thanks for trying it!

I've not checked what you did, but the short answer is "That is possible (behind the flag)".

You might want to enabled the flag, `chrome://flags/#web-bundles`, which is documented in 
https://chromium.googlesource.com/chromium/src/+/refs/heads/main/content/browser/web_package/using_web_bundles.md.

cc: @irori @horo-t, if you can add a comment or a guide.

**Comment by horo-t** [comment]
Loading web bundle from network feature ([crbug](https://crbug.com/1018640)) is implemented behind `WebBundlesFromNetwork` flag. You have to pass `--enable-features=WebBundlesFromNetwork` runtime argument when launching Chrome.

But currently we don't support signed web bundle nor signed exchange of web bundle.
Chrome can load pages in the unsigned web bundle if the page's URL is under the path scope of the web bundle's URL. See [this document](https://github.com/WICG/webpackage/blob/main/explainers/navigation-to-unsigned-bundles.md#loading-an-authoritative-unsigned-bundle) for more details.

**Comment by hayatoito** [comment]
@horo-t  Thanks for the info!

@bitdivine Could you share which documents you referred?

We might want to update our documents to clarify the current status.

**Comment by bitdivine** [comment]
Thank you very much for the information.  I will try what is possible now.  The feature does seem as if it would be very useful.  Do you know whether it is being worked on actively?  If I wait in hope, am I likely to be overjoyed in a few months, disappointed when it does not come in a year, or is it hard to say?

**Comment by bitdivine** [comment]
Regarding documents, my main sources were:
- [Internet-Draft:
draft-yasskin-wpack-bundled-exchanges](https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html)
- [The github repo with `bundle`](https://github.com/WICG/webpackage/tree/main/go/bundle) - this does say that chrome support is experimental.  I was unsure whether that information is current.  It seems that it is!
- [web.dev article from 2019: "Get started with Web Bundles"](https://web.dev/web-bundles/)

**Comment by hayatoito** [comment]
Thanks!
I've filed an issue to update the document, https://bugs.chromium.org/p/chromium/issues/detail?id=1246774.

> Do you know whether it is being worked on actively? If I wait in hope, am I likely to be overjoyed in a few months, disappointed` when it does not come in a year, or is it hard to say?

It is hard to say.
We are currently working on a [subresource loading with WebBundles](https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading.md) use case, which is a slightly different use case.

We always appreciate feedback so that we can focus on important tasks. If you can share compelling use cases, that would be welcomed!

**Comment by bitdivine** [comment]
Ooh, that could also work for my use case.  Thank you for the link and for all the status updates.
