### ISSUE TITLE
Better integration of Service Worker and Subresource Web Bundle loading

### ISSUE THREAD

**Issue by horo-t** [WICG/webpackage#676]
The [explainer](https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading.md) of "Subresource loading with Web Bundles" doesn't address the expected behavior of the service worker fetch interception.
And in the current Chromium implementation, if the service worker of the page intercepts the web bundle request, the subsequent subresource requests can’t be served from the web bundle.

As a short term solution, this CL https://crrev.com/c/3145076 sets the SkipServiceWorker flag of the both requests. So the inner subresource can be served from the web bundle.

As a long term solution, we need to figure out the ideal design of the service worker integration. And we need to introduce an option argument {skip_service_worker: false (default is true)}.

Chromium side issue: https://crbug.com/1240424

**Comment by hayatoito** [comment]
Tagging a meta issue #708 here.
We have to specify `{skip_service_worker: false (default is true)}` in the spec.

**Comment by hayatoito** [comment]
Note: We are closing this issue with PR #743, however, it's worth mentioning that it is a short term solution.

We can re-open this issue anytime when we need to revisit this issue. Please feel free to re-open this!
