### ISSUE TITLE
Fix GitHub Actions `spec-prod.yml` error: No 'dfn' refs found for 'creating' with for='['ReadableStream']'.

### ISSUE THREAD

**Issue by hayatoito** [WICG/webpackage#680]
GitHub Action's `spec-prod.yml` workflow has been failing:

> [INFO] Build bikeshed document "loading.bs" (common)…
>    $ bikeshed --die-on=warning spec "loading.bs" "loading.bs.built.html" 
>      LINE ~1538: No 'dfn' refs found for 'creating' with for='['ReadableStream']'.

Is there anyone who is willing to fix this?

**Comment by hayatoito** [comment]
We want bikeshed expert. :)

**Comment by jyasskin** [comment]
Looks like we need to change that call to use https://streams.spec.whatwg.org/#other-specs-rs-create, which involves checking how the interface changed. I'll look into it.
