### ISSUE TITLE
Look into Merkle trees for quick access to parts of large resources

### ISSUE THREAD

**Issue by jyasskin** [WICG/webpackage#69]
For example, we might want to be able to start playing a large video file without hashing the whole thing.

See https://tools.ietf.org/html/draft-thomson-http-mice for one approach.

**Comment by bmeck** [comment]
can you clarify? we aren't encoding the resource so random access should work. Or are you talking about allowing integrity checks on ranges within a resource?

**Comment by jyasskin** [comment]
Allowing integrity checks on ranges within a resource.

**Comment by jyasskin** [comment]
#108 defined a generic way to identify a header that guards the content. The `MI` header from draft-thomson-http-mice then provides incremental integrity for the beginning of a resource, and when there's a demonstrated need we can define another header or content encoding within the `MI` header that uses a balanced Merkle tree for random access integrity checks.
