### ISSUE TITLE
Do we need the :method header?

### ISSUE THREAD

**Issue by jyasskin** [WICG/webpackage#70]
https://github.com/WICG/webpackage/pull/60#discussion_r121227994 points out that we might not want to store the [`:method` header](http://httpwg.org/specs/rfc7540.html#HttpRequest) in requests. We only know of uses of `GET` requests, and having the ability to code other methods might cause bugs.

**Comment by bmeck** [comment]
I vote it is uneeded.

**Comment by ibnesayeed** [comment]
From an archival perspective it might be important to keep it. Also, apart from `GET` there are other methods that might be useful, such as, `HEAD` and `OPTIONS` or any other methods that do not change the state of the resource.

**Comment by jyasskin** [comment]
#360 is merged. If a particular archival use case comes up, we can reopen the question.

**Comment by ibnesayeed** [comment]
@jyasskin do we have a way to support `OPTIONS` request without this header? If not, then how will the CORS requests work that need pre-flight requests?
