### ISSUE TITLE
Start an internet-draft

### ISSUE THREAD

**Issue by jyasskin** [WICG/webpackage#71]
This supports the [IETF submission](https://mailarchive.ietf.org/arch/msg/dispatch/NQ0deHSsRvt4BL4alk_WYVnhhvo). It has to happen before they close the RFC database from July 3 until the [Prague meeting](http://ietf.org/meeting/99/index.html).

We can use https://github.com/cabo/kramdown-rfc2629 to author in markdown, and https://github.com/martinthomson/i-d-template to build with Travis CI.

**Comment by lrosenthol** [comment]
@jyasskin can you explain why you want to have this work happen through IETF instead of W3C?

**Comment by jyasskin** [comment]
@lrosenthol The IETF has way more expertise developing file formats than the W3C. One can even think of the packaging format as a transport protocol with particular constraints on the connection, which is squarely in the IETF's domain.

That said, the W3C is definitely the right place to specify how browsers load the format, and, for publications, how publication-readers load it, which could be different from browsers. I expect to have 2+ specifications as a result: one in the IETF, and one or more in the W3C and maybe elsewhere.

**Comment by lrosenthol** [comment]
@jyasskin Historically, I would agree with you about that. However, with the IETF (which has over a decade) of packaging and format experience joining the W3C this year, you now have a group of people who not only have the knowledge *but* are also engaged to this work.  I am not sure that the IETF folks will be as engaged.  In a related bit, I would think that having the browser vendors at the W3C aligning on the format as a "web archive" would be a win.

I would strongly prefer that we keep the entire thing, but broken into separate work items as you suggest, would be best.
