### ISSUE TITLE
Failed to read metadata of Web Bundle file: Index section: exchange URL is not valid.

### ISSUE THREAD

**Issue by anacrolix** [WICG/webpackage#730]
I get this trying to load a wbn resource in Chrome. Other sites work like the web.dev.wbn example. I'm not sure what is wrong.

**Comment by irori** [comment]
`dump-bundle -i your-bundle.wbn` might give you a better error message.
How did you create the wbn?

**Comment by anacrolix** [comment]
I created it with `gen-bundle -har ... -primaryURL ... -o blah.wbn`. I have tried dumping it, I didn't see anything useful in the output. Is there something specific I should check for?

**Comment by hayatoito** [comment]
[Issue Triage]
Let me close this tentatively. If you still have an issue, please feel free to update the issue. e.g. paste the output or upload the created bundle.

BTW, I've heard that the bundles linked from https://web.dev/web-bundles/ are outdated. That uses the old `b1` format, which is no longer supported in the latest chromium.

**Comment by anacrolix** [comment]
I'm not sure why this is closed, it's neither fixed, and I had no feedback on my question. Cheers

**Comment by irori** [comment]
Could you try it again once Chrome is upgraded to 106? Chrome 106 includes some error message improvements.

**Comment by anacrolix** [comment]
Yes, I can do that.
