### ISSUE TITLE
Path prefix?

### ISSUE THREAD

**Issue by domenic** [WICG/webpackage#732]
The explainer [states](https://github.com/WICG/webpackage/blob/fcb50a7ed74c521f94adaef1955831beba302d19/explainers/subresource-loading.md#script-based-api_:

> Records the resources and delays fetching a subresource specified there if a subresource's origin is the [same origin](https://html.spec.whatwg.org/#same-origin) as the bundle's origin and its [path](https://url.spec.whatwg.org/#concept-url-path) contains the bundle's path as a prefix.

However, none of the examples have the bundle's path contained as a prefix of the resource path. E.g. `dir/subresources.wbn` is not a prefix of `dir/a.js`.

Which is correct, the examples or the explainer text?

**Comment by hayatoito** [comment]
Thanks for filing an issue!

The example is correct. The explainer's wording is inaccurate and needs to be fixed. That is not a simple prefix match.

Our intention is, what is called, *Path Restriction*, which is also used in ServiceWorker.
https://w3c.github.io/ServiceWorker/#path-restriction

The specification has an internal issue for that: https://wicg.github.io/webpackage/subresource-loading.html#issue-3afe47ae
