### ISSUE TITLE
Improve relative URLs support in Go/JavaScript bundle tools

### ISSUE THREAD

**Issue by irori** [WICG/webpackage#739]
Although relative URLs are now explicitly allowed in WebBundles (#647), our tools do not have good support for them. Currently the only way to create a bundle with relative URL is to use a HAR file that contains relative URLs.

**Comment by hayatoito** [comment]
FYI. [google/webbundle](https://github.com/google/webbundle) supports a relative URL in [v0.3](https://github.com/google/webbundle/releases/tag/webbundle-cli-v0.3.1), though [google/webbundle](https://github.com/google/webbundle) is still experimental.
