### ISSUE TITLE
Chromium error when loading minimal wbn: Cannot parse the size of section-lengths

### ISSUE THREAD

**Issue by josephrocca** [WICG/webpackage#751]
I tried running the "hello world" code in the [npm package](https://github.com/WICG/webpackage/tree/main/js/bundle) readme after adding the latest relative URL support changes (that aren't published on NPM package yet):

```js
const wbn = require('wbn');
const builder = new wbn.BundleBuilder();

builder.addExchange(
  "/",                                 // URL
  200,                                 // response code
  {'Content-Type': 'text/html'},       // response headers
  '<html>Hello, Web Bundle!</html>',   // response body (string or Uint8Array)
);  

fs.writeFileSync('out.wbn', builder.createBundle());
```

But I get `ERR_INVALID_WEB_BUNDLE` when trying to run it on latest Chrome Dev with the Web Bundles flag enabled.

The error in the console is: "Failed to read metadata of Web Bundle file: Cannot parse the size of section-lengths."

I tried searching for this error but wasn't able to find any details about what might be going on.

@irori, assuming I'm doing something wrong here, is there a pull request that I could make to the npm package readme that would make it more clear how to produce a minimal working wbn file?

Thanks!

**Comment by irori** [comment]
In Chrome, WebBundles with relative URLs are only supported for [subresource loading](https://chromium.googlesource.com/chromium/src.git/+/refs/heads/master/content/browser/web_package/subresource_loading_origin_trial.md). So, you cannot navigate into such bundles.

Sorry for the confusion! We should improve error messages.

Btw, when I tried opening a wbn created with the above JS code, I got ERR_INVALID_WEB_BUNDLE with a different console error message:
```
Failed to read metadata of Web Bundle file: Index section: exchange URL is not valid.
```
I wonder why you got a parse error. What is your Chrome version (chrome://version/)?

**Comment by josephrocca** [comment]
@irori Thanks for the reply! Chrome version: 103.0.5060.24 (Official Build) dev (64-bit) Linux

I tried changing `"/"` to `"https://example.com"`, but it produced the same error. Would you be able to show a code example to produce a minimal "hello world" web bundle?

**Comment by josephrocca** [comment]
Oh, sorry! I think it's because I was using main branch of the repo rather than the published NPM package. But when using the published NPM package I get this error (when using `https://example.com` as URL): "Web Bundle is missing the Primary URL to navigate to."

**Comment by josephrocca** [comment]
@irori Oh, sorry! I think it's because I was using main branch of the repo rather than the published NPM package. But when using the published NPM package I get this error (when using `https://example.com` as URL): "Web Bundle is missing the Primary URL to navigate to."

**Comment by hayatoito** [comment]
[Issue Triage]
It seems we can close this issue.
