### ISSUE TITLE
Is primaryURL still required on b2?

### ISSUE THREAD

**Issue by alexandercerutti** [WICG/webpackage#761]
Hello, I was experimenting a bit with web bundles.
I've downloaded `go/bundle` and set up everything needed.

If I print the help instructions for `gen-bundle`, I can see two interesting things:

1) `-version string / The webbundle format version. Possible values are: 'b1' and 'b2' (default "b2")`
2) `-primaryURL string / Primary URL`

On [gen-bundle here on github](https://github.com/WICG/webpackage/tree/main/go/bundle#gen-bundle), README reports that

> -primaryURL specifies the bundle's main resource URL. This URL is also used as the fallback destination when browser cannot process the bundle. If bundle format is b1, this option is required.

So I do expect that creating a bundle without primaryURL works fine with version b2.
For some reason, if I try to generate one without primaryUrl and open it with Chrome 102 with Web Bundles flag enabled, the bundle cannot be opened. I've generated it with the following command:

So, where does the problem lay?
Is the statement "v2 does not require primaryURL" false, or Chrome requires primaryURL?

Here I'm going to attach the bundles version of the todo-preact-app (with updated dependencies) that does not open:

[todomvc.wbn.zip](https://github.com/WICG/webpackage/files/8815850/todomvc.wbn.zip)

Thank you.

**Comment by hayatoito** [comment]
Thanks for trying.

I guess you are:

A) navigating to the wbn itself (aka "navigate-to-bundle")

instead of

B) loading subresoruces from the web bundle (aka "subresource loading with webbundles").

For the former case, primary URL is still required. Chrome visits the primary URL.
For your wbn, I guess `primary url` should be 'https://preact.todom.vc"

For the latter case, primary URL is not required. That is not used.

**Comment by alexandercerutti** [comment]
Hi @hayatoito, thank you for your answer!
Yes, I was trying to pick and drop the bundle into Chrome.

This difference is not clear _at all_ in CLI and in documentation between the two cases.

So, once you drop the bundle in Chrome, it visits the primary URL and attempts to go online and fetch the latest resources from there.

Otherwise, it goes offline with bundled resources. Am I right? Hence, `primaryURL` should be just the URL you would visit normally, is it? What If a site is not available (yet?) online, but just locally? If I try to set `primaryUrl` to `localhost:8080` (or the explicit IP) I get:

> bundle: No exchange for primary URL http://127.0.0.1:8080

In the case of subresources loading, instead, the browser loads the content as "support" just like any other js and CSS asset. Isn't it?

And to test subresources loading, a subscription to [the origin trial](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/content/browser/web_package/subresource_loading_origin_trial.md) is required, isn't it?

**Comment by hayatoito** [comment]
> Otherwise, it goes offline with bundled resources. Am I right?

Yes. Suppose that you dropped the bundle into Chrome, you can see the following URL in the address bar:

file:///<file_system_path_in_your_local_machine>/todomvc.wbn?https://preact-todom.vc/

It's offline. The chrome doesn't visit the *actual* https://preact-todom.vc/ site. The chrome just *uses* the resource in the bundle.

> In the case of subresources loading, instead, the browser loads the content as "support" just like any other js and CSS asset. Isn't it?

Yes.


> And to test subresources loading, a subscription to [the origin trial](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/content/browser/web_package/subresource_loading_origin_trial.md) is required, isn't it?

A subscription to the origin trial is not required if you enable the flag:
[How` to try this feature locally](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/content/browser/web_package/subresource_loading_origin_trial.md#how-to-try-this-feature-locally).

Note: We are shipping this feature for M104. From M104, the flag  is not required.

**Comment by hayatoito** [comment]
Just for reference:

For the purposes of testing "Subresource loading with WebBundles" feature, the following is the very minimum page which uses this feature:

- Test page: https://hayatoito-deno-deploy-test.deno.dev/2022-06-01/web-bundle-subresource-loading.html
- source: https://github.com/hayatoito/deno-deploy-test/tree/main/static/2022-06-01

Note there is no guarantee that I will keep this site live.

**Comment by alexandercerutti** [comment]
Oh, I see. Thank you very much @hayatoito!

I've successfully generated a web bundle that runs on localhost. So, `primaryURL` needs to be an HTTPS but the server is not required to be active or to serve HTTPS.

> It's offline. The chrome doesn't visit the actual https://preact-todom.vc/ site. The chrome just uses the resource in the bundle.

Uhm, I see that DevTools still try to access the primaryURL, and even if the server is not active, they still receive back HTTP 200 on resources loading... so I can guess that DevTools are still not updated yet to support WebBundles and show more detailed information and that the experiment in the browser just acts like a proxy for HTTP requests. Am I right?

___

Now I have to test subresources loading. I guess I'll have to specify the files or upload a HAR.

Just as early feedback, I actually don't like how resources must be explicitly declared in the `webbundle`'s json in HTML: honestly, I can see people creating a big bundles containing hundreds of small js and css files for a sake of modularity. Having to explicit them one by one also with explicit URL might bring to have a bloated HTML files, even if they might be generated.

With modules federation, we don't usually have HTML files but just JS files that get loaded remotely and on demand. So here I guess that the best solution would be to create a JS API that would allow Javascript to register the source of that file (just like it happens with 

With modules federation, also, we might have several components and functionality that we might support and lazy load, but still we should write them all in the HTML.

I can, anyway, understand that the `resources` field is needed to make the browser understand where the resource should be fetched from. I was thinking to possible solutions to fix this, also in relation to the possible usage of Webbundles with module federation, but there are a lot of details to think to and I didn't figured out a good solution yet. Maybe a JS API that resembles WebComponents Custom Registry API?

**Comment by hayatoito** [comment]
> Uhm, I see that DevTools still try to access the primaryURL, and even if the server is not active, they still receive back HTTP 200 on resources loading...

Hmm. If a browser fetches a resource from the network if the bundle has a resource for it, I think that should be considered as a bug.

BTW, although "navigate-to-bundle" feature was implemented behind the flag, we are not working on this feature actively. It's a low priority for now.



> Just as early feedback, I actually don't like how resources must be explicitly declared in the `webbundle`'s json in HTML

We can use `scopes` to avoid enumerating every resources.

https://github.com/WICG/webpackage/blob/main/explainers/subresource-loading.md#defining-the-scopes

e.g. https://github.com/hayatoito/deno-deploy-test/blob/main/static/2022-06-01/web-bundle-subresource-loading.html
```
 <script type="webbundle">
    {
      "source": "./resources/wbn/simple.wbn",
      "scopes": ["./"]
    }
  </script>

```

**Comment by alexandercerutti** [comment]
> > Uhm, I see that DevTools still try to access the primaryURL, and even if the server is not active, they still receive back HTTP 200 on resources loading...
> 
> Hmm. If a browser fetches a resource from the network if the bundle has a resource for it, I think that should be considered as a bug.

Just to be clearer, I mean this in the screenshot (but localhost:8080 has not an application listening at the moment of the screenshot). So I guess it is read from bundle but still reported as read from the network.

<img width="1137" alt="immagine" src="https://user-images.githubusercontent.com/5442545/171855999-9a1bd6b7-e469-4efb-8802-9e319174406e.png">

___

> BTW, although "navigate-to-bundle" feature was implemented behind the flag, we are not working on this feature actively. It's a low priority for now.

Okay, so your focus is on sub-resources loading instead of whole website containers?

___

About `scopes`, okay well, that's interesting. 🤔

Anyway, FYI, I edited my previous message. I f****d up a few things while reviewing the text 😂 

Thank you for the answers!!

**Comment by alexandercerutti** [comment]
Thank you! If it is not a problem, I'd like to keep this open for a while, just in case of other questions

**Comment by hayatoito** [comment]
[Issue Triage]
Let me close this issue. Thanks!
