### ISSUE TITLE
Web Bundles that don't have an origin?

### ISSUE THREAD

**Issue by josephrocca** [WICG/webpackage#762]
Is there a special URL value for cases where the `wbn` file wasn't downloaded from an origin/server, but was instead created as a "standalone" bundle? Something like `about:webbundle` or `webbundle://` or `http://webbundle`, or some special value/protocol like that?

I'm wondering about the resource policy/security implications of having a dummy URL that's actually a real website like example.com, but it also just feels strange/unclean to have to use an arbitrary dummy URL for bundles that don't have a server/http location.

Another potential solution would be to use an `ipfs` content-addressed URL, or similar, if a protocol like that is eventually supported.

This seems like a fairly basic requirement so apologies if I've missed something in the explainer or other docs.

**Comment by hayatoito** [comment]
I think the question is for "navigate-to-bundle" case. Although a web bundle format itself supports "a relative URL", I don't think that works for "navigate-to-bundle" case, where an absolute URL is required to make the navigation work.

@irori  Do you have any insights? I think the answer would be "Unfortunately, the dummy URL is required"...

**Comment by josephrocca** [comment]
Thanks for your reply! Yes, this is in reference to the "navigate-to-bundle" case. If a special value/protocol/tld is unlikely to be created, then perhaps best practice could be to use `.example` as the TLD? It is apparently reserved:

> By publication of RFC 2606 in 1999, the [Internet Engineering Task Force](https://en.wikipedia.org/wiki/Internet_Engineering_Task_Force) reserved the DNS labels [example](https://en.wikipedia.org/wiki/.example), [invalid](https://en.wikipedia.org/wiki/.invalid), [localhost](https://en.wikipedia.org/wiki/.localhost), and [test](https://en.wikipedia.org/wiki/.test) so that they may not be installed into the [root zone](https://en.wikipedia.org/wiki/DNS_root_zone) of the Domain Name System.

> The reason for reservation of these top-level domain names is to reduce the likelihood of conflict and confusion.[[1]](https://en.wikipedia.org/wiki/.example#cite_note-rfc-1) This allows the use of these names for either documentation purposes or in local testing scenarios.

https://en.wikipedia.org/wiki/.example

**Comment by hayatoito** [comment]
[Issue Triage]

It seems we can close this issue, in favor of https://github.com/WICG/webpackage/issues/763.
