### ISSUE TITLE
Study the openZIM format

### ISSUE THREAD

**Issue by kelson42** [WICG/webpackage#79]
I kind of wonder why the ZIM format seems not to have been studied properly? Even if the format is not so rigorously documented and still lacks a few tools around it, this is probably the most used web content offline distribution file format.

General purpose web sites:
* http://www.openzim.org/
* http://www.kiwix.org/

For developers:
* https://github.com/openzim/
* https://github.com/kiwix/

**Comment by bmeck** [comment]
@kelson42 can you define "seems not to have been studied properly"

It seems much more limited in capabilities / lacking signing / lacking requirements of things like Node.

**Comment by kelson42** [comment]
@bmeck 

It's true about signing. That looks something relatively easy to specify and implement. Would make sense to make it on openzim side.

What do you mean exactly about "requirements of things like Node". The README talks about self-exactracting things? Is that what you mean? If "yes", have you an extended explanation about the requirement?

**Comment by bmeck** [comment]
Node constraints: https://github.com/WICG/webpackage/issues/33

Other things like supporting `link:`/`transfer-encoding:`/`cache-control:`/`expires:` style metadata and subpackages were the main things when commenting on limited capabilities.

**Comment by kelson42** [comment]
@bmeck Thx for the confirmation about self-extracting, but I do not really understand how data package with self-extracting could be used a  standard. This will be de-facto designed for one system/arch. Do you have somewhere the use case? Why having the decompressor in the package is so important?

**Comment by bmeck** [comment]
@kelson42 use case is to create single file executables (of which both Node and Electron are interested), moving it to the host env means variations on how such is performed and loss of interoperability. Node certainly can use other formats than WebPackage such as `.zip` and `.asar` already but those are not standardized and agreed upon.

**Comment by jyasskin** [comment]
Thanks to the pointer to an existing format. You're right that I didn't study it when designing the packaging format. Looking at it now, I think the lack of signing prevents us from just adopting it. The rest of the format looks tailored to Wikipedia articles: is it being used for other kinds of websites as well?

**Comment by kelson42** [comment]
It is a bit late, but this is only for documentation:
* The format does still not provide content signing. The ticket is here https://github.com/openzim/libzim/issues/40
* The format is suited for any kind of static content, not only Wikipedia & co. We provide already a lot of different content see https://download.kiwix.org/zim/
