### ISSUE TITLE
Prefetch page TLS certificate expired

### ISSUE THREAD

**Issue by pepawel** [WICG/webpackage#884]
I don't know if this is the correct place, because I don't know who maintains the SXG prefetch testing page. It appears this page is no longer accessible because the TLS certificate expired today:

https://signed-exchange-testing.dev/prefetch/

HSTS is used, so the browser doesn't even allow to bypass TLS certificate validation.

If the issue should be addressed elsewhere, I would appreciate your guidance.

**Comment by pepawel** [comment]
As the domain is HSTS preloaded, one can't even disable HSTS in `chrome://net-internals/#hsts`.

The only workaround for now is to type following when Chrome error appears: `thisisunsafe`

**Comment by banaag** [comment]
Apologies for the issue, this has now been fixed.

**Comment by pepawel** [comment]
Thank you very much Allan!
